### ISSUE TITLE
"Metal" support for M1...

### ISSUE THREAD

**Issue by bbecausereasonss** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#1]
But is there anyway to get this to work on M1 (Metal) without CUDA?

**Comment by BBC-Esq** [comment]
> But is there anyway to get this to work on M1 (Metal) without CUDA?

I could probably modify the code to do that.  I don't have an Apple so would you be willing to test it if I dedicate some time?  Probably won't take too long.

**Comment by BBC-Esq** [comment]
> Yes would love to test it out.

Alright, can you friend me on the LM Studio Discord?

**Comment by bbecausereasonss** [comment]
Same name? Cant find you. I'm becausereasons
