### ISSUE TITLE
For OCR feature

### ISSUE THREAD

**Issue by clickclack777** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#100]
https://github.com/VikParuchuri/surya

**Comment by BBC-Esq** [comment]
Already considered this, which relies in part on the tesseract library.  I've also looked at  tesseract itself as well as onnx...which pymupdf can use internally at time.  Onnx is extremely slow and unreliable, and I wasn't able to get a tesseract working reliably either.

At this juncture, I'm open to a pull request if someone else wants to work on this, but it'd need to be extremely reliable.  Other cheap software like  "Wondershare PDF Element" has much more reliable OCR features, my ScanSnap scanner uses ABBYY OCR capabilities...and so on...OCR is extremely complex to implement, ESPECIALLY if you want to extract tables, if your text is at an angle, fonts, footnotes, etc...Don't have the time myself to handle this considering the borderline free OCR stuff out there...
