### ISSUE TITLE
Feature request: Stop Generating button

### ISSUE THREAD

**Issue by clickclack777** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#102]
Would be great to have a small red button to the right of the "Submit question" to stop text generation from the LLM when you see that the response isn't what you are looking for, the answer is lengthy and you want to regenerate the answer.

**Comment by BBC-Esq** [comment]
Can't promise a small red button per se, but I agree it'd be useful, especially if the response looks to be long and a person doesn't have powerful GPU and it'd eat up a lot of time waiting to complete.  Same with stopping playing Bark if a user wants.

**Comment by BBC-Esq** [comment]
Completed.

**Comment by clickclack777** [comment]
Just a simple square with the text "Stop generating" will do. :)
