### ISSUE TITLE
feature request: prompt input

### ISSUE THREAD

**Issue by clickclack777** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#103]
Which prompt is the plug-in using since LM Studio ignores pre-prompt in server mode? Would it be possible to add a custom prompt input?

**Comment by BBC-Esq** [comment]
LM Studio only ignores the prefix/suffix if you disable the prompt formatting and delete any entries in the prefix/suffix boxes.  Yags stated that this is an error and that it should ignore the prefix/suffix in the LM Studio entry boxes as long as the setting is disabled, even if there's text in there.  He said he'll fix this...but as of now, you must do both.

Second, my program allows you to:

Select a prefix/suffix from the pulldown menu, click update settings, and it'll use them.

Or manually enter a prefix/suffix, click update settings, and it'll use the custom prompt.

You can see this working by examining the config.yaml file after you click update settings.

**Comment by clickclack777** [comment]
OK. Just to confirm, new settings in your app kicks in when submitting a questions right?
