### ISSUE TITLE
feature request: copy generated text

### ISSUE THREAD

**Issue by clickclack777** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#104]
Would it be possible to add a functionality to copy the generated text? When I mark and copy the text now, the out always ends up in the font Times. Not a biggy but would be great to use a san serif typefont instead like Helvetica (if this can be changed on your side).

**Comment by BBC-Esq** [comment]
I'm not aware of a way to specify the font with which you want copied text to appear...As far as I know...

**Comment by clickclack777** [comment]
How about the text copying function?

**Comment by BBC-Esq** [comment]
If the feature request is just a button to copy the LLM's response without having to manually select the text...yes.

**Comment by clickclack777** [comment]
Yes, that's the primary request. Thanks!
