### ISSUE TITLE
Ability to force chain of thought

### ISSUE THREAD

**Issue by uiukin** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#106]
Might be already existing, but currently i don't find a way to force a chain of thought approach with the models that are provided with context from vector db.
E.g. Main Request -> Narrowed request based on previous one (arguments, explaining the logic behind returned result, etc.) -> Further granularity and so on.

P.S. This is a fantastic effort, thank you so much for everything you did!

**Comment by BBC-Esq** [comment]
Thanks for the compliment.  Unfortunately I don't have any plans to create a memory or anything similar like you mentioned.  What you're seeking can be achieve by using key words as well as rephrasing your question and using the appropriate embedding model.  With some experience, you can easily get a context that contains the exact answer you're looking for within 1-4 contexts if you do this....
