### ISSUE TITLE
Small bug: theme custom stylesheet doesn't work in v3.4

### ISSUE THREAD

**Issue by clickclack777** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#119]
When changing style sheet in v3.4 nothing happens.

**Comment by BBC-Esq** [comment]
Fixed by importing "QApplication" in this snippet from ```utilities.py```.  Will be incorporated into the next bug fix/major release:
```
from PySide6.QtWidgets import QMessageBox, QApplication
```
