### ISSUE TITLE
vision models specifically made for MacOS?

### ISSUE THREAD

**Issue by BBC-Esq** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#123]
Possibly implement for MacOs users due to other vision models not working with MacOS currently:

[https://huggingface.co/apple?search_models=aim](https://huggingface.co/apple?search_models=aim)

**Comment by delfireinoso** [comment]
Yes when whe try to chose a vision model the program crashes

**Comment by BBC-Esq** [comment]
Will incorporate later when I have someone who will help test on macos.
