### ISSUE TITLE
v3.4.1: Installation steps result in PIP dependency errors with torch & triton in Windows & WSL

### ISSUE THREAD

**Issue by sangemaru** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#124]
On reaching the `pip install -r requirements.txt` step, it will error out. This is being installed in WSL2.

```
Installing collected packages: sentencepiece, pytz, PyAudio, nvidia-ml-py, monotonic, InstructorEmbedding, flatbuffers, filetype, docx2txt, bitsandbytes, av, zstandard, xxhash, xlrd, wrapt, websockets, watchdog, uvloop, tzdata, triton, tqdm, threadpoolctl, termcolor, tenacity, tabulate, soupsieve, sniffio, six, shiboken6, scipy, safetensors, regex, rapidfuzz, PyYAML, python-magic, python-iso639, python-dotenv, pyparsing, pypandoc, PyMuPDFb, pydantic, pyarrow-hotfix, pyarrow, pulsar-client, psutil, protobuf, packaging, overrides, olefile, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, mypy-extensions, multidict, Markdown, lz4, lxml, jsonpointer, jsonpath-python, joblib, humanfriendly, httptools, hnswlib, h11, greenlet, fsspec, frozenlist, exceptiongroup, et-xmlfile, emoji, einops, duckdb, dill, click, chardet, backoff, attrs, async-timeout, yarl, uvicorn, typing-inspect, SQLAlchemy, scikit-learn, python-docx, python-dateutil, PySide6-Essentials, PyMuPDF, openpyxl, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nltk, multiprocess, msg-parser, marshmallow, langsmith, langdetect, jsonpatch, huggingface-hub, ctranslate2, coloredlogs, clickhouse-connect, beautifulsoup4, anyio, aiosignal, watchfiles, tokenizers, starlette, PySide6-Addons, posthog, pandas, onnxruntime, nvidia-cusolver-cu12, marshmallow-enum, langchain-core, dataclasses-json, aiohttp, unstructured-client, transformers, torch, PySide6, openai, langchain, faster-whisper, fastapi, unstructured, torchvision, datasets, chromadb, accelerate, sentence-transformers, optimum
  Attempting uninstall: triton
    Found existing installation: triton 2.2.0
    Uninstalling triton-2.2.0:
      Successfully uninstalled triton-2.2.0
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2023.4.0
    Uninstalling fsspec-2023.4.0:
      Successfully uninstalled fsspec-2023.4.0
  Attempting uninstall: torch
    Found existing installation: torch 2.2.0+cu118
    Uninstalling torch-2.2.0+cu118:
      Successfully uninstalled torch-2.2.0+cu118
  Attempting uninstall: torchvision
    Found existing installation: torchvision 0.17.0+cu118
    Uninstalling torchvision-0.17.0+cu118:
      Successfully uninstalled torchvision-0.17.0+cu118
**ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchaudio 2.2.0+cu118 requires torch==2.2.0, but you have torch 2.1.2 which is incompatible.
xformers 0.0.24+cu118 requires torch==2.2.0, but you have torch 2.1.2 which is incompatible.**
Successfully installed InstructorEmbedding-1.0.1 Markdown-3.5.1 PyAudio-0.2.14 PyMuPDF-1.23.7 PyMuPDFb-1.23.7 PySide6-6.6.1 PySide6-Addons-6.6.1 PySide6-Essentials-6.6.1 PyYAML-6.0.1 SQLAlchemy-2.0.25 accelerate-0.25.0 aiohttp-3.9.3 aiosignal-1.3.1 anyio-3.7.1 async-timeout-4.0.3 attrs-23.2.0 av-10.0.0 backoff-2.2.1 beautifulsoup4-4.12.3 bitsandbytes-0.41.3.post2 chardet-5.2.0 chromadb-0.3.29 click-8.1.7 clickhouse-connect-0.7.0 coloredlogs-15.0.1 ctranslate2-3.24.0 dataclasses-json-0.6.3 datasets-2.16.1 dill-0.3.7 docx2txt-0.8 duckdb-0.9.2 einops-0.7.0 emoji-2.10.1 et-xmlfile-1.1.0 exceptiongroup-1.2.0 fastapi-0.85.1 faster-whisper-0.10.0 filetype-1.2.0 flatbuffers-23.5.26 frozenlist-1.4.1 fsspec-2023.10.0 greenlet-3.0.3 h11-0.14.0 hnswlib-0.8.0 httptools-0.6.1 huggingface-hub-0.20.3 humanfriendly-10.0 joblib-1.3.2 jsonpatch-1.33 jsonpath-python-1.0.6 jsonpointer-2.4 langchain-0.0.341 langchain-core-0.0.6 langdetect-1.0.9 langsmith-0.0.85 lxml-5.1.0 lz4-4.3.3 marshmallow-3.20.2 marshmallow-enum-1.5.1 monotonic-1.6 msg-parser-1.2.0 multidict-6.0.4 multiprocess-0.70.15 mypy-extensions-1.0.0 nltk-3.8.1 nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-8.9.2.26 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-ml-py-12.535.108 nvidia-nccl-cu12-2.18.1 nvidia-nvjitlink-cu12-12.3.101 nvidia-nvtx-cu12-12.1.105 olefile-0.47 onnxruntime-1.16.3 openai-0.28.0 openpyxl-3.1.2 optimum-1.15.0 overrides-7.7.0 packaging-23.2 pandas-2.0.3 posthog-3.3.4 protobuf-4.25.2 psutil-5.9.5 pulsar-client-3.4.0 pyarrow-15.0.0 pyarrow-hotfix-0.6 pydantic-1.10.14 pypandoc-1.12 pyparsing-3.1.1 python-dateutil-2.8.2 python-docx-1.1.0 python-dotenv-1.0.1 python-iso639-2024.1.2 python-magic-0.4.27 pytz-2023.4 rapidfuzz-3.6.1 regex-2023.12.25 safetensors-0.4.2 scikit-learn-1.4.0 scipy-1.12.0 sentence-transformers-2.2.2 sentencepiece-0.1.99 shiboken6-6.6.1 six-1.16.0 sniffio-1.3.0 soupsieve-2.5 starlette-0.20.4 tabulate-0.9.0 tenacity-8.2.3 termcolor-2.3.0 threadpoolctl-3.2.0 tokenizers-0.15.1 torch-2.1.2 torchvision-0.16.2 tqdm-4.66.1 transformers-4.36.0 triton-2.1.0 typing-inspect-0.9.0 tzdata-2023.4 unstructured-0.11.6 unstructured-client-0.8.1 uvicorn-0.27.0.post1 uvloop-0.19.0 watchdog-3.0.0 watchfiles-0.21.0 websockets-12.0 wrapt-1.16.0 xlrd-2.0.1 xxhash-3.4.1 yarl-1.9.4 zstandard-0.22
```

**Comment by BBC-Esq** [comment]
Are you using the latest 3.4.1 release?

**Comment by sangemaru** [comment]
@BBC-Esq , yes, latest 3.4.1. Just tried a fresh install under plain Windows, no WSL, same exact conflict.

**Comment by sangemaru** [comment]
When trying to run `python gui.py` in this state I encounter the following error:

```
(src) PS C:\work\AI\ChromaDB-Plugin-for-LM-Studio-3.4\src> python gui.py
C:\work\AI\ChromaDB-Plugin-for-LM-Studio-3.4\src\Lib\site-packages\transformers\utils\generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
C:\work\AI\ChromaDB-Plugin-for-LM-Studio-3.4\src\Lib\site-packages\transformers\utils\generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
C:\work\AI\ChromaDB-Plugin-for-LM-Studio-3.4\src\Lib\site-packages\transformers\utils\generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
C:\work\AI\ChromaDB-Plugin-for-LM-Studio-3.4\src\Lib\site-packages\transformers\utils\generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
Traceback (most recent call last):
  File "C:\work\AI\ChromaDB-Plugin-for-LM-Studio-3.4\src\metrics_bar.py", line 31, in run
    power_usage_percent, power_limit_percent = collect_power_metrics(handle)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\work\AI\ChromaDB-Plugin-for-LM-Studio-3.4\src\metrics_bar.py", line 163, in collect_power_metrics
    power_limit = pynvml.nvmlDeviceGetPowerManagementLimit(handle) / 1000.0
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\work\AI\ChromaDB-Plugin-for-LM-Studio-3.4\src\Lib\site-packages\pynvml.py", line 2551, in nvmlDeviceGetPowerManagementLimit
    _nvmlCheckReturn(ret)
  File "C:\work\AI\ChromaDB-Plugin-for-LM-Studio-3.4\src\Lib\site-packages\pynvml.py", line 897, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.NVMLError_NotSupported: Not Supported
doh set to ""  --  SystemOnly
QPainter::end: Painter ended with 4 saved states
QPainter::end: Painter ended with 4 saved states
QPainter::end: Painter ended with 4 saved states
```

**Comment by BBC-Esq** [comment]
> @BBC-Esq , yes, latest 3.4.1. Just tried a fresh install under plain Windows, no WSL, similar conflict though different versions:
> 
> ```
> Installing collected packages: torch, xformers
>   Attempting uninstall: torch
>     Found existing installation: torch 2.1.2+cu118
>     Uninstalling torch-2.1.2+cu118:
>       Successfully uninstalled torch-2.1.2+cu118
> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> torchaudio 2.1.2+cu118 requires torch==2.1.2+cu118, but you have torch 2.2.0+cu118 which is incompatible.
> torchvision 0.16.2+cu118 requires torch==2.1.2+cu118, but you have torch 2.2.0+cu118 which is incompatible.
> Successfully installed torch-2.2.0+cu118 xformers-0.0.24+cu118
> ```

Regarding this first issue you mentioned...

PyTorch just released a new version (2.2.2) and the old version was 2.1.2...And it's been weird how they rolled it out...Have you seen my updated instructions here?

![image](https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio/assets/108230321/8d652152-ec7e-41cc-a01a-1a167ed2a11a)

Regarding the second issue you mentioned...

The error stems from the ```metrics_bar.py``` script beginning on line 31:

![image](https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio/assets/108230321/59e0025e-cec9-4250-ba3b-01c58d1d3cfd)

I'm not sure why you're receiving this error because line 31 isn't even supposed to execute unless an nvidia gpu is present, which is impossible not a macos system so...

However, my immediate concern is this error you received:
```
C:\work\AI\ChromaDB-Plugin-for-LM-Studio-3.4\src\Lib\site-packages\transformers\utils\generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
Traceback (most recent call last):
```

When I tested installing PyTorch 2.2.2 (again my program uses 2.1.2 currently) I received this error.  My ```requirements.txt``` specifies "transformers" 4.36 and it's up to 4.37.2 as of this morning...therefore, it's possible that this error will go away once I confirm that my program will work with the newer version and update ```requirements.txt``` accordingly.

I say all this because, the fact you received this error means that you didn't have the correct version of pytorch installed.  Make sure you've installed the correct version and let me know if you still get the error regarding the "nvml" library regarding ```metrics_bar.py```.

The github instructions explain the new installation procedure of pytorch but I'll explain a little more for you:

Go here: [https://download.pytorch.org/whl/](https://download.pytorch.org/whl/)

You'll need to install three pytorch libraries named "torch," "torchaudio," and "torchvision".

Regarding "torch..."

You want version 2.1.2.  Do a search like this:

![image](https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio/assets/108230321/f22446eb-4ab2-496d-bb5e-193ab93746b0)

Choose the correct one depending on your cpu architecture (e.g. x86/arm) and the version of python you have installed (e.g. python 3.10 or 3.11).  For example, if you are using Python 3.11 and your cpu architecture is x86:
![image](https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio/assets/108230321/cbe0db1d-d90d-4098-9c68-6eb7b9d189e0)

Right click on this wheel and click "copy link".

Go back to your terminal window and run the command ```pip3 install [paste the link you copied here```.  For example, regarding the above wheel the command you'd run would be as follows:

```pip3 install https://download.pytorch.org/whl/cpu/torch-2.1.2-cp311-none-macosx_10_9_x86_64.whl#sha256=76d37967c31c99548ad2c4d3f2cf191db48476f2e69b35a0937137116da356a1```

**Comment by BBC-Esq** [comment]
Please see my corrected comment above if you accidentally read it before I corrected it.

**Comment by sangemaru** [comment]
> Regarding the first issue, it's strange since my latest setup.py file should install the correct versions of pytorch based on which version of python you have (3.10 or 3.11). Did you use setup.py?

Yes, i used the setup.py script. As far as I can tell it first installed torch 2.1.2, then uninstalled it, possibly due to latest xformers.



> You've just installed the correct version of the "torch" library from pytorch that I have thus far confirmed works with my program. You must do the same for the "torchaudio" and "torchvision" libraries.

I installed it, but interestingly I still get an xformers dependency error:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
xformers 0.0.24+cu118 requires torch==2.2.0, but you have torch 2.1.2+cu118 which is incompatible.
```

So I went ahead and ran `https://download.pytorch.org/whl/cu118/xformers-0.0.23%2Bcu118-cp311-cp311-win_amd64.whl#sha256=1e03af99f27612a0099045f835332c5ee4cb5c2df4c0dbcff73a91684a3ec8d4` but then this rolled torch back to 2.1.1, so now I have:

```ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchaudio 2.1.2+cu118 requires torch==2.1.2+cu118, but you have torch 2.1.1 which is incompatible.
torchvision 0.16.2+cu118 requires torch==2.1.2+cu118, but you have torch 2.1.1 which is incompatible.
```

So I replaced that xformers package with version xformers-0.0.23.post1+cu118-cp311-cp311-win_amd64.whl instead: `pip install https://download.pytorch.org/whl/cu118/xformers-0.0.23.post1%2Bcu118-cp311-cp311-win_amd64.whl#sha256=8c232bccf88e19de91b545a2b29886c5684bf5d1f7014b6a3d126e481b5e01ee`

This seems to have resolved my dependencies and I was able to run `python gui.py` successfully. Thanks for the support.

**Comment by BBC-Esq** [comment]
You're welcome.  For future reference, I'm about to issue a release in the next few days that'll have an updated ```setup.py``` script for Windows that should hopefully resolve the pytorch-related errors/conflicts.  Pytorch threw me for a loop when they made version 2.2.2 the latest stable version, but that version causes errors with some other libraries.  And moreover, if you run the generic pip install pytorch it automatically chooses 2.2.2, so I'm including specific pip install commands to specific wheels that pertain to version 2.1.2 until I can get all the dependencies working together.  Stay tuned.  Coming from a non-programmer's perspective too so...this is still a learning experience for me as well!

**Comment by sangemaru** [comment]
Haha, sorry friend 😂 The moment you started maintaining your own public github repo followed by hundreds and forked by dozens, you definitely gained the Programmer title.
