### ISSUE TITLE
Bark Response not working under Macos

### ISSUE THREAD

**Issue by pl2k2000** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#127]
I clicked Bark Response after I get results from LM Studio, voice processed fine but no sound was played:
bark_module.py: Bark model loaded.
Size = Small
Quant = float16
The BetterTransformer implementation does not support padding during training, as the fused kernels do not support attention masks. Beware that passing padded batched data during training may result in unexpected outputs. Please refer to https://huggingface.co/docs/optimum/bettertransformer/overview for more details.
bark_module.py: Better Transformer selected.
Processing Sentences:   0%|                                  | 0/15 [00:00<?, ?it/s]bark_module.py: Creating audio.
en_speaker_0_semantic_prompt.npy: 100%|████████| 2.86k/2.86k [00:00<00:00, 9.95MB/s]
en_speaker_0_coarse_prompt.npy: 100%|██████████| 8.32k/8.32k [00:00<00:00, 15.3MB/s]
en_speaker_0_fine_prompt.npy: 100%|████████████| 16.5k/16.5k [00:00<00:00, 17.4MB/s]
Processing Sentences:  33%|████████▎                | 5/15 [08:30<21:22, 128.23s/it]Processing Sentences: 100%|█████████████████████████| 15/15 [14:39<00:00, 58.60s/it]
bark_module.py: All audio finished playing.
bark_module.py: Bark models removed from memory.

**Comment by BBC-Esq** [comment]
What's your system setup again?

**Comment by pl2k2000** [comment]
Macbook Air M2 24GB Ram

**Comment by BBC-Esq** [comment]
My initial suggestion would be to make sure that my program has the necessary permissions to access your audio device:

System Permissions: On macOS, applications need permission to access the microphone, and sometimes this can extend to audio playback functionalities depending on system security settings. Ensure that your Python environment or terminal has the necessary permissions to output audio.

Secondly, are you sure you followed these instructions when installing:
![image](https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio/assets/108230321/19d891a4-0d78-4b9d-9008-4a7f3d84d72a)

**Comment by BBC-Esq** [comment]
Here's a possible alternative:

https://huggingface.co/mlx-community/mlx_bark

**Comment by BBC-Esq** [comment]
When I have time I might revisit this.
