### ISSUE TITLE
Request: Allow for API or External Web Access

### ISSUE THREAD

**Issue by NobelAT** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#14]
I primarily use LLM's for work. LM Studio allows for API access, and with that, I can integrate all kinds of other tools into my LLM workflow. I would really like to be able to incorporate document chat into those workflows. It would be fantastic if there was a way to allow access to this over the web. 

Whether that is a locally hosted webapp, or via an API, it would be a fantastic feature to enable.

**Comment by BBC-Esq** [comment]
Can you give me an example of how it would be used like this?  I'm not quite sure...

**Comment by BBC-Esq** [comment]
No response...

**Comment by mzeidhassan** [comment]
Hi @BBC-Esq ,

Let me jump in and give you an example.

Imagine we're operating a Gradio app designed to interact with the LM Studio Server API. Currently, when employing your plugin directly through the GUI, it seamlessly facilitates document queries and answers through your GUI. However, if I pose the same query via my app — which connects to the LM Studio Server API — the answers returned are solely sourced from the LLM, disregarding the indexed documents in our vector database established by your plugin.

Our goal is to integrate our vector database into the API workflow. This way, when we make API calls through our app, the system should tap into the indexed documents to provide results.

Does this make sense?
