### ISSUE TITLE
portaudio error on MacOS

### ISSUE THREAD

**Issue by BBC-Esq** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#18]
ps: tried to install this on my mac.. and I get this error:
---
```
python3 gui.py
Traceback (most recent call last):
  File "/Users/ac/Documents/mc2/software/databases/chroma/chroma_for_llmstudio/ChromaDB-Plugin-for-LM-Studio-main/src/gui.py", line 1, in <module>
    from PySide6.QtWidgets import (
ModuleNotFoundError: No module named 'PySide6'
(/Users/ac/Documents/mc2/software/databases/chroma/chroma_for_llmstudio/ChromaDB-Plugin-for-LM-Studio-main/src/conda_chroma_env) 
```

_Originally posted by @abcnow in https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio/issues/11#issuecomment-1786976653_

**Comment by BBC-Esq** [comment]
PySide6 should be installed when you install the requirements.txt, per my online instructions.  If that doesn't fix it, let me know...

**Comment by abcnow** [comment]
I get his error while installing your "requirements.txt":

creating build/temp.macosx-10.9-universal2-cpython-39/src/pyaudio
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/Headers -arch arm64 -arch x86_64 -Werror=implicit-function-declaration -Wno-error=unreachable-code -DMACOS=1 -I/usr/local/include -I/usr/include -I/opt/homebrew/include -I/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/include/python3.9 -c src/pyaudio/device_api.c -o build/temp.macosx-10.9-universal2-cpython-39/src/pyaudio/device_api.o
      src/pyaudio/device_api.c:9:10: fatal error: 'portaudio.h' file not found
      #include "portaudio.h"
               ^~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for PyAudio
Failed to build PyAudio
ERROR: Could not build wheels for PyAudio, which is required to install pyproject.toml-based projects
(/Users/ac/Documents/mc2/software/databases/chroma/chroma_for_llmstudio/ChromaDB-Plugin-for-LM-Studio-main/src/conda_chroma_env)

**Comment by abcnow** [comment]
ok.. I went ahead and install and now i am getting this error after I entered "python3 gui.py":
-------
python3 gui.py
Traceback (most recent call last):
  File "/Users/ac/Documents/mc2/software/databases/chroma/chroma_for_llmstudio/ChromaDB-Plugin-for-LM-Studio-main/src/gui.py", line 8, in <module>
    import server_connector
  File "/Users/ac/Documents/mc2/software/databases/chroma/chroma_for_llmstudio/ChromaDB-Plugin-for-LM-Studio-main/src/server_connector.py", line 2, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'
(/Users/ac/Documents/mc2/software/databases/chroma/chroma_for_llmstudio/ChromaDB-Plugin-for-LM-Studio-main/src/conda_chroma_env)

**Comment by BBC-Esq** [comment]
Aha!  I've seen that error before actually but haven't implemented a change because it was with a friend of mine's computer that was really old, and not even with my program.  But now it's confirmed.  Can you try installing portaudio before my requirements.txt.  I believe the command is "brew install portaudio".

The issue 99% stems from the use of PyAudio, which is a wrapper for PortAudio.  Another library named "sounddevice" is also a wrapper but doesn't have the compatibility issues from what I've read.  I could easily switch out libraries but want to troubleshoot a little first.

**Comment by BBC-Esq** [comment]
There's also conflicts sometimes when installing things with brew versus normal python installation commands (e.g. pip).  Wish I had a mac to help troubleshoot, but we can try a little.

**Comment by abcnow** [comment]
fantastic.. that "brew install portaudio" solved the problem

**Comment by abcnow** [comment]
and I am now I am running the program.. anything in particular that you want me to test here?

**Comment by abcnow** [comment]
the fonts are supposed to be black? I am color blind so.. I can hardly see those colors

**Comment by BBC-Esq** [comment]
> fantastic.. that "brew install portaudio" solved the problem

Excellent!  I'll update my installation instructions because that step wasn't there!

**Comment by abcnow** [comment]
![New Note](https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio/assets/35501607/60c9a8fc-a8d9-4af0-9b6a-16ab06f915d6)

**Comment by BBC-Esq** [comment]
> and I am now I am running the program.. anything in particular that you want me to test here?

Not right this instant, but let's continue our discussion in the help needed issue if you don't mind?  I'm sure in the coming days I could use some testing, but right now just experiment with it a little.  Wow, no, the font is supposed to be white...

**Comment by abcnow** [comment]
fantastic.. yes.. let's do it.. ok.. I would love to chat with some documents.. is this possible with your plugin and llmstudio?

**Comment by abcnow** [comment]
by the way .. shoot me an email at acnow19@gmail.com and probably we can chat faster via whatsapp

**Comment by BBC-Esq** [comment]
Yep!

**Comment by BBC-Esq** [comment]
this is what it should look like: https://raw.githubusercontent.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio/main/example.png

**Comment by abcnow** [comment]
ok.. I can see that better :)

**Comment by abcnow** [comment]
PS: I have around 15 gb of data that I would love to ingest.. around 300-500 pdfs..
1. I wonder if we could have like a place where you could see the documents to ingest and keep track of all of them.. something that you could just drop all the files and organize them by folders and subfolders
2. would we need a better way to link db to ingested documents and we just let chroma do it automatically?
