### ISSUE TITLE
add color schemes to choose from

### ISSUE THREAD

**Issue by BBC-Esq** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#19]
the fonts are supposed to be black? I am color blind so.. I can hardly see those colors

_Originally posted by @abcnow in https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio/issues/18#issuecomment-1788032366_

**Comment by BBC-Esq** [comment]
User had this issue but would be nice to have some help with it.

**Comment by BBC-Esq** [comment]
Try replacing the "fusion" at the very bottom of gui.py with "windows" or "windowsvista" and see if it improves the viewing experience.  Otherwise, I can try and create some color schemes eventually.  I searched online and you can also try "macos", which I just found might work.

**Comment by BBC-Esq** [comment]
Also, check this out...might work better for you: [link here](https://stackabuse.com/styling-pyqt6-applications-default-and-custom-qss-stylesheets/)

**Comment by abcnow** [comment]
perfect.. let me try it

**Comment by abcnow** [comment]
![with_macos](https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio/assets/35501607/29afec0e-2fe8-4b0e-98d1-4ae891ab3bce)

**Comment by abcnow** [comment]
that's when I change it to "macos"

**Comment by abcnow** [comment]
![with_windows](https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio/assets/35501607/8c08a75f-f35d-416e-858a-eee269e279a5)
and with windows

**Comment by BBC-Esq** [comment]
Try this and see what all available styles there are...I think there are more. 
![image](https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio/assets/108230321/43bce224-1a62-4f95-a8e8-b0a7da3aa24b)

**Comment by BBC-Esq** [comment]
Open my folder where my scripts are, activate the virtual environment...type Python3  Then the first command, hit enter, then the second command above, and hit enter, let me know what you get...It varies on OS I believe, this will help me test my program actually.  Here's what I get on Windows...
![image](https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio/assets/108230321/c6a3f392-d991-4cee-acf9-37ff51f0cf98)

**Comment by BBC-Esq** [comment]
For colorblind people, if you'll go [to this website](https://www.webfx.com/web-design/color-picker/) and try the colors below that were recommended to me, and let me know which are good to show contrast and stuff, which go good together, which don't, I will incorporate a scheme into the GUI.  Feel free to expand upon this list too.

Background: Light gray (#F5F5F5)
    Primary Text: Dark gray (#333333)
    Secondary Text: Medium gray (#777777)
    Primary Action (e.g., buttons): Sky blue (#4A90E2)
    Secondary Action: Pale blue (#BFDFFF)
    Highlight: Soft yellow (#FFEB3B)
    Error: Soft red (#FFCDD2)
    Success: Soft green (#C8E6C9)
    Neutral Action (e.g., disabled buttons): Light gray (#E0E0E0)

**Comment by abcnow** [comment]
ok.. this is what I got
-----
$ python3
Python 3.9.6 (default, May  7 2023, 23:32:44) 
[Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> print(QStyleFactory.keys())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'QStyleFactory' is not defined
>>>

**Comment by BBC-Esq** [comment]
Do the following order:

Create the virtual environment and...

1 - Python3
2 - Hit enter key
3 - from PySide6.QtWidgets import QStyleFactory
4 - Hit enter key
5 - print(QStyleFactory.keys())
6 - Hit enter key

**Comment by BBC-Esq** [comment]
> ## ok.. this is what I got
> 
> $ python3 Python 3.9.6 (default, May 7 2023, 23:32:44) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > print(QStyleFactory.keys())
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > NameError: name 'QStyleFactory' is not defined

Let me know if you get these instructions.  I'm not sure if github notifies you when I just send you a message on here or if I have to quote your last message within my message, like I did with this message, in order for you to get notified.

**Comment by abcnow** [comment]
ok perfect.. those steps on top work.. I am not sure why.. I had to reinstall again PySide6

**Comment by BBC-Esq** [comment]
The commands should work, as long as you "activate" the same virtual environment just like when running my program.

**Comment by abcnow** [comment]
Ok..I got busy here .. so I went back and updated in the script to 'macOS" and also wtih 'Windows" and 'Fusion" but it keeps showing not the right colors

**Comment by abcnow** [comment]
if you want I can give you access to my laptop.. probably that can speed up this process :)

**Comment by BBC-Esq** [comment]
Cab you try running the commands in the way I described above?  We can try a screen share sometime if need be.  Also, it would be helpful if you could help pick out a color scheme.

**Comment by BBC-Esq** [comment]
Lack of interest.

**Comment by BBC-Esq** [comment]
Reopened and added a bunch of color schemes, including one for colorblind people!
