### ISSUE TITLE
option to perform OCR on pdfs that need it to work with the database

### ISSUE THREAD

**Issue by BBC-Esq** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#21]
PDFs must have ocr done on them or already have the text...sometimes it's hard to tell with hundreds of pdfs...an option to possibly perform ocr when creating the database or and/or an option to perform it by selecting specific files.

**Comment by twobob** [comment]
https://github.com/cpacker/MemGPT/issues/88#issuecomment-1783364914 <-- notes

**Comment by BBC-Esq** [comment]
Lack of interest + plenty of software that can do this, albeit not at scale.
