### ISSUE TITLE
Add a feature to use the exciting Bark models to have the response from LM Studio speak outloud

### ISSUE THREAD

**Issue by BBC-Esq** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#23]
Bark is just cool, but it requires a lot of horsepower to run...but sounds scary accurate like real human...

**Comment by twobob** [comment]
I second this, from both angles. it will not be even close to fluent, taking around 30s to queue up even a sentence.  Needs some love to make "good"

**Comment by BBC-Esq** [comment]
Closing this for lack of interest/help.  May re-open later.

**Comment by BBC-Esq** [comment]
v2.7.3 Windows specific release has basic functionality.  Can expand/fine-tune that, therefore, closing this core issue.
