### ISSUE TITLE
says ctranslate2 not compiled with cuda support

### ISSUE THREAD

**Issue by BBC-Esq** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#27]
Hello, I have a M1 Mac and I'm trying to run this. Installation was perfectly ok, but when I execute the GUI ("python3 gui.py" ) I got the following error: 

![image](https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio/assets/1958613/ea8b39e4-69d8-4bbf-b310-14419677cfba)

Can I disable the CUDA support on the translate package to just use CPU?

Great work, btw!

_Originally posted by @RuiPedroLeal in https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio/issues/11#issuecomment-1823199285_

**Comment by BBC-Esq** [comment]
Will respond as soon as I can, might be after the holiday.

**Comment by BBC-Esq** [comment]
Are you installing with Brew or another method...or following the instructions on the github readme?

**Comment by RuiPedroLeal** [comment]
Hello. Following the instructions on the GitHub by the letter. Everything ok till that point.

**Comment by BBC-Esq** [comment]
I know we don't know each other, but would you be interested in a screen share on Discord?
 Had one other person encountered that message, but they never responded halfway through troubleshooting.
 And I'd like to get to the bottom of it.

**Comment by RuiPedroLeal** [comment]
A quick update, managed to get 10m to look into this. From what I can see, the device parameter is coming empty on the "update_quantization" function on the "gui_tabs_tools_transcribe.py" file  (it's strange, but seems the config is not loading?).

I just quickly removed the IF from CPU vs CUDA and it's working:

![image](https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio/assets/1958613/1a8f63cb-d24f-4090-a3b2-51622726c0e3)

If I have a bit today I will check the loading configuration part. 

(Guess you're US based, so happy thanksgiving to you!)

**Comment by BBC-Esq** [comment]
I am U.S. based but have some time this morning....but probably would be better tomorrow sometime honestly.  Feel free to DM me on Discord...am looking into how you fixed the issue in order to determine if it's a permanent fix or a patch that disables certain functionality...Is the program working otherwise now?

**Comment by BBC-Esq** [comment]
...My script should first check of CUDA support is available for the transcription feature...and if so, it should obtain the supported quantizations for the whisper/transcription models with "cuda" as an argument and "cpu" as an argument.  It then updates this dynamically when a user chooses "gpu" for the compute device...it shows updated quantization options in another pulldown menu...

This is coincidentally something I was planning on revamping.  I was working on only checking the available compute devices (cpu, cuda, and mps) when the program stars...then checking the supported quantizations for each detected device...saving this to a config.yaml file, then pulling the info from config.yaml when needed...No need to run the command from the Ctranslate2 library each and every freaking time a user changes a pulldown menu...

But please let me know if the program is working perfectly otherwise for you.  We can hold off on a screenshare now I think.

**Comment by BBC-Esq** [comment]
This issue should be addressed in the newest release version 2.7.
 If I don't hear from you, I'll close this issue out in a couple days.

**Comment by Ahmet0691** [comment]
Things I see missing:
1-) Button to stop the query when it is made
2-) When a document is selected and a Vector Database is created, when I start the program again for the second time, I feel the need to perform the same operation again for the same document. (I have already created the vector database, why do I have to create it again?)
3-) You selected a document, clicked Create Vector Database, made your query and closed the program. Later, when you select a new document, it includes the previous document and creates vectors for both documents. (To prevent this, it is necessary to delete the previously selected document from Docs_Fo_DB.)
4-) Just like LM-Studio, I think it should be started in cmd without writing any lines of code.

**Comment by BBC-Esq** [comment]
Closing.  Someone else confirmed that version 2.7 indeed fixed this issue.
