### ISSUE TITLE
Unicode errors? (Will probably submit PR)

### ISSUE THREAD

**Issue by TheRealBeef** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#34]
Traceback (most recent call last):
  File "C:\ChromaDB-Plugin-for-LM-Studio-2.7\src\gui_threads.py", line 19, in run
    response = server_connector.ask_local_chatgpt(self.user_question)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ChromaDB-Plugin-for-LM-Studio-2.7\src\server_connector.py", line 153, in ask_local_chatgpt
    write_contexts_to_file_and_open(contexts)
  File "C:\ChromaDB-Plugin-for-LM-Studio-2.7\src\server_connector.py", line 49, in write_contexts_to_file_and_open
    file.write(context + "\n\n\n")
  File "C:\Users\luser\.conda\envs\chromadb\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u0105' in position 152: character maps to <undefined>

**Comment by BBC-Esq** [comment]
Thanks for this.  Do you have the fuller print statement?  Also, do you know which type of file your were trying to process?  .txt files are specifically encoded using utf-8 but I didn't specify that for other file extensions.

**Comment by TheRealBeef** [comment]
It wasn't an issue with reading the files in to the database, but when you click "Test Embeddings" and it tries to read from the database.

**Comment by BBC-Esq** [comment]
I see...so when creating the .txt file when "test embeddings" is enabled...That might make sense.  Should be a 5 minute fix...

**Comment by TheRealBeef** [comment]
The fix is already in a PR for you above "Added handling for UTF-8 when testing embeddings"

**Comment by TheRealBeef** [comment]
Closed, I'll resubmit the PR later on :)

**Comment by BBC-Esq** [comment]
Should have some updated scripts in an hour or so.
