### ISSUE TITLE
Feature: Grey out/Disable Submit button until streaming is complete

### ISSUE THREAD

**Issue by TheRealBeef** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#39]
With the streaming capability, there isn't (afaik) an API call to stop generating/streaming once submitted, so greying out or disabling the submit button until the last stream is complete is something I'd like to do in the next few days or so

**Comment by BBC-Esq** [comment]
Like it, I might actually be able to knock this out tonight...but I'm going to create another issue about cancelling the LLM's response...or if a user does that within LM Studio, we have to be prepared.  For example, if a user stops LM Studio from providing a response and the checkbox is greyed out, but before a response is provided...or a partial response is provided...what happens to the Submit Questions button?

**Comment by TheRealBeef** [comment]
If it's cancelled from LM studio side / loses connection it should cancel the stream ... I would consider to put the logic for unlocking the button alongside the logic for removing the database from memory around here https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio/blob/630f19dc0a6c7a506db8ca509ef7ac4b2059e8e8/src/server_connector.py#L168 and testing this functionality

**Comment by BBC-Esq** [comment]
Are you familiar with "signals" and "slots' of the pyside6/aka  QT framework?  I think that'd be the approach...it's "thread safe" as I've come to find out but I'm still early on in learning it...

**Comment by TheRealBeef** [comment]
Address in PR #50

**Comment by BBC-Esq** [comment]
When the amount of text sent to the LLM exceeds the model's context limit (e.g. 4096), for example, when sending excessive contexts - like 50 - "processing..." is displayed on the button and it doesn't revert to its prior state without closing and restarting the program.  Here's a visual: 
![image](https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio/assets/108230321/4390f930-9461-46c0-9dd0-07d0d2286ebb)

**Comment by BBC-Esq** [comment]
Fix implemented here just in case: https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio/commit/79d2eef1f3fc1a822ccd5bbcccf35bd2dffbe6a9
