### ISSUE TITLE
Feature: UI Button to display plaintext/markdown

### ISSUE THREAD

**Issue by TheRealBeef** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#40]
Add a UI button to display Markdown or Plaintext - likely makes sense just above the textbox

Depending on how complex it is to implement, may also make sense to have a button to increase/decrease text size here as well.

![image](https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio/assets/84393940/4c383025-6eee-41e5-a1fa-e949c77235ed)

**Comment by BBC-Esq** [comment]
Sounds good, but I'd like to keep the options at the bottom near the buttons, perhaps next to the Test Embeddings checkbox if possible.

**Comment by TheRealBeef** [comment]
It can fit well there too and I'm not picky so sounds like a plan

**Comment by BBC-Esq** [comment]
There's also space immediately below the start/stop recording buttons I'm torn about.  I've experimented with scripts that break the "metrics_bar" into 2 portions.  E.g., the usage meters would only go halfway to the right (regardless if a user resizes the GUI, and the right 50% of that space I was considering putting system messages.  For example, "downloading embedding model" or "transcribing question" or "whisper model ready to transcribe question" stuff like that...stuff that's typically in the command prompt.

Eventually, the command prompt will be dispensed with altogether unless perhaps a "debugging" checkbox to display it.  That'll probably be awhile...around the time I figure out how to create a single .exe file to distribute this program in...

**Comment by TheRealBeef** [comment]
I'll probably not start on this before Christmas given our increase in workload. If you happen to want to pursue it in the meantime, just le me know, otherwise I'll probably get to starting on it in the interim period between Christmas/New Years

**Comment by BBC-Esq** [comment]
No problem!  I'll let you know if I get to it before but probably won't be able to so...

**Comment by BBC-Esq** [comment]
I'm debating change the widget type from text to "html" in which the LLM's response is put...that'd enable me to have hyperlinks to documents and/or citations after the LLM's response.  Thoughts?  It could possibly impact your project of adding html and/or markdown options...

**Comment by BBC-Esq** [comment]
Closed for lack of interest.
