### ISSUE TITLE
Cancel LLM's response midstream or error handling when cancelled midstream or test embeddings is checked.

### ISSUE THREAD

**Issue by BBC-Esq** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#41]
Two related issues:

Investigate whether it's possible to cancel the LLM's response midstream (e.g. if it's taking too long, a user wants to change their query slightly on second thought, etc.), if this is even possible from the program's perspective....or perhaps LM Studio has to be used to do this?

Second, if the submit question button is disabled before the LLM provides a full response (so a user can't double-click it and get incoherent responses) then make sure the button is re-enabled.  So it'd need to be re-enabled if the response is cut short...not response has been provided...no connection to the LLM because the "test embeddings" button was checked, and any other permutation of circumstance that users might encounter.

**Comment by TheRealBeef** [comment]
The second one is no issue - all works as you'd expect in PR#50.

The first one is still up in the air as to the answer

**Comment by BBC-Esq** [comment]
Closed for lack of interest/motivation regarding the second item.
