### ISSUE TITLE
possibly change the voice recorder and transcription functionality backends

### ISSUE THREAD

**Issue by BBC-Esq** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#45]
Currently using ctranslate2/faster-whisper.  They're not compatible with CUDA 12+ out of the box, they require compiling apparently.  Thus, need to start looking at alternatives that support the same backends - Intel MKL, Ruy, CUDA (obviously), etc.  Something that supports AMD acceleration would be nice as well.

CUDA 12+ is starting to become mandatory.  For example, Flash Attention 2 is amazing...but is only supported by CUDA 12+.  Same with other technologies.

ALSO, using faster-whisper is relatively long-winded in a script compared to the "pipelines" of huggingface, for example.  Let's discuss.

**Comment by TheRealBeef** [comment]
What are the alternatives that are available?

**Comment by BBC-Esq** [comment]
They might be starting to discuss making ctranslate2 support CUDA12 without having to compile from source...see here...,[https://github.com/OpenNMT/CTranslate2/issues/1250](https://github.com/OpenNMT/CTranslate2/issues/1250)

Last updated today by me...But CUDA 12+ came out in October 2022 so...I can't wait much longer...and I don't want users to have to compile from source to simply use my program...

Possible alternatives might be...

[https://github.com/Vaibhavs10/insanely-fast-whisper](https://github.com/Vaibhavs10/insanely-fast-whisper) (but lacks compatibility)

using the normal "pipeline" from huggingface since it's received speedups in the last year

[https://github.com/ggerganov/whisper.cpp/releases/tag/v1.5.0](https://github.com/ggerganov/whisper.cpp/releases/tag/v1.5.0), which I'm leaning towards.  They've reportedly fixed the issues that kept them behind ctranslate2 (IMHO), albeit months and months after ctranslate2 did, and the support community for llama.cpp is generally much wider...and I believe AMD gpu acceleration is supported so...

**Comment by BBC-Esq** [comment]
I forgot to mention, this might be a viable alternative, but I'm debating the tradeoff in speed versus DistilWhisper only being able to handle English: [https://github.com/huggingface/distil-whisper](https://github.com/huggingface/distil-whisper).  Plus, it's my understanding that ctranslate2 actually handles distil-whisper so...that might make the transition easier.

Also, perhaps a user can choose to use distil-whisper for everything (e.g. voice recording and transcription of a file) if it's in English...and then choose regular Whisper if there are other languages present.  I do want to eventually translate files in other languages to put into the vector database, or at least have that option so...

**Comment by BBC-Esq** [comment]
Considering possibly using "distil whisper" models (A) in place of whisper models or (B) adding them as an extra option.

Distil whisper is only for English transcription but since my program has yet to implement "translation..." and even if it does, distil-whisper could easily be added as an additional faster option for english-only users...Plus the additional programming time to change to .cpp or other implementations...plus the speedup backends that ctranslate2 already has for cpu accleration...might not be worth switching after all.

We'll see...

**Comment by BBC-Esq** [comment]
Tried Whisper.cpp and it didn't work as well, and tried another, but didn't have the backend support.  Plus, ctranslate2 should be getting CUDA 12 support soon.
