### ISSUE TITLE
Ensure Python 3.12 compatibility.

### ISSUE THREAD

**Issue by BBC-Esq** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#46]
Python 3.12 is now in debug mode only...all major substantive releases are out and it's considered "stable," but this program might not work with 3.12 so...

Need to update to Python 3.12 compatibility while STILL maintaining Python 3.11 compatibility, a new endeavor for me...

**Comment by TheRealBeef** [comment]
I wouldn't sweat 3.12 unless one of the other dependencies you're trying to use requires it. There is always a push by users to have the latest/greatest but it's not always necessary

**Comment by BBC-Esq** [comment]
Agreed...There are a couple that don't work with 3.12, but as more people install 3.12 I'd like to be compatible with both just in case...medium priority though ATM...

**Comment by BBC-Esq** [comment]
Verified today that PyTorch does NOT currently support Python 3.12 so...this issue is being put on the backburner.  Usually there's a lag until newer stuff is supported so...check back in a few months.

**Comment by BBC-Esq** [comment]
On second thought, closing until PyTorch advertises that it's compatible with Python 3.12...and able to verify that other dependencies are as well...which is not a simple task.
