### ISSUE TITLE
Switch pdf loader library from pdfminer.six to PyMuPDF

### ISSUE THREAD

**Issue by BBC-Esq** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#47]
BANE...PyMuPDF's loader is 40x faster than pdfminer.six, which this program currently uses.  However, pdfminer.six works with Chromadb out of the box.  I'm convinced that pymupdf loader will work with ChromaDB, but haven't been able to get it working yet...The way it creates "documents" (the term of art that chromadb uses) is differnt than pdfminer.six.  It should be possible to get the correct format of the "document' by examining the source code of the pymupdf library and/or chromadb.

Spent 10+ hours thus far...multiple test scripts...work in progress...Appreciate any help.

**Comment by BBC-Esq** [comment]
Fixed finally!  Coming in next release. 40x speedup for loading pdf files.

**Comment by TheRealBeef** [comment]
Impressive!

**Comment by BBC-Esq** [comment]
You don't realize how long I've been struggling to fix this...It involved fixing the actual sourcecode from Langchain though.  lol.  Not conventional at all...Nothing wrong with my scripts themselves.

**Comment by BBC-Esq** [comment]
Completed as of version 2.7.2.
