### ISSUE TITLE
implement optical character recognition

### ISSUE THREAD

**Issue by BBC-Esq** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#49]
Add optical character recognition for pdfs that don't have it done on them yet.

**Comment by BBC-Esq** [comment]
Options being looked at are onnxruntime or pytesseract

**Comment by clickclack777** [comment]
OCR for images as well please, now that we have vision in 3.0 :)

**Comment by BBC-Esq** [comment]
Yep!

**Comment by BBC-Esq** [comment]
anyone have any good suggested python libraries.  I'm already aware of tesseract.

**Comment by BBC-Esq** [comment]
Closed for OCR regarding pdf files, but will work informally on OCR when using vision models if possible.  Plenty of free software has OCR for pdf files.
