### ISSUE TITLE
Feature Request: Option for setting LM Studio when it's a different IP

### ISSUE THREAD

**Issue by zarlor** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#51]
I have a use case where I would primarily be working from my laptop which has fewer resources than my desktop so as a nice method of splitting the workload I have LM Studio running on my robust desktop in server made and this ChromaDB Plugin running on my laptop but I can't see a way in the settings to tell it the IP address of my desktop, only the ability to change the port number. I'm assuming it's hard coded to search "localhost" for this communication on port 1234? If so I'd certainly like to request adding that feature in, but if it's already there I certainly apologize that I didn't see it, so maybe the request would be to maybe put it into the Server/LLM Settings if it is someplace else?

**Comment by BBC-Esq** [comment]
That feature isn’t there but feel free to make a request.

Sincerely,

Blair Chintella, Esq.

***@***.******@***.***>
404-556-7057

This communications is being sent by or on behalf of a lawyer and may be privileged, confidential or protected by the attorney/client privilege relationship.  If you inadvertently received this e-mail please delete it immediately and/or notify the sender.

From: Lenny Zimmermann ***@***.***>
Sent: Friday, December 15, 2023 5:45 PM
To: BBC-Esq/ChromaDB-Plugin-for-LM-Studio ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [BBC-Esq/ChromaDB-Plugin-for-LM-Studio] Feature Request: Option for setting LM Studio when it's a different IP (Issue #51)


I have a use case where I would primarily be working from my laptop which has fewer resources than my desktop so as a nice method of splitting the workload I have LM Studio running on my robust desktop in server made and this ChromaDB Plugin running on my laptop but I can't see a way in the settings to tell it the IP address of my desktop, only the ability to change the port number. I'm assuming it's hard coded to search "localhost" for this communication on port 1234? If so I'd certainly like to request adding that feature in, but if it's already there I certainly apologize that I didn't see it, so maybe the request would be to maybe put it into the Server/LLM Settings if it is someplace else?

**Comment by zarlor** [comment]
Already requested :) (that email got to you form the request on GitHub). I think I can also just manually change the connection_str entry in the config.yaml file? I'll give that a try for a workaround. Thanks!

**Comment by TheRealBeef** [comment]
Curious to see how it works out :)

**Comment by BBC-Esq** [comment]
> Already requested :) (that email got to you form the request on GitHub). I think I can also just manually change the connection_str entry in the config.yaml file? I'll give that a try for a workaround. Thanks!

Also interested to know if it worked.

**Comment by zarlor** [comment]
> > Already requested :) (that email got to you form the request on GitHub). I think I can also just manually change the connection_str entry in the config.yaml file? I'll give that a try for a workaround. Thanks!
> 
> Also interested to know if it worked.

Changing the connection_str entry? I don't think it did, but I'm not positive. I noticed it seems to change it back I think on restart or when, or even if, it reads that file directly, but initial testing didn't seem to work. Unfortunately to really test it I would probably need to be able to run both LM Studio and this on that same laptop and the combo doesn't quite want to work right, but then again LM Studio no longer wants to work right on my desktop anyway, so I haven't been able to get a good test without fixing that problem (which probably has a lot more to do with needing to do a Windows re-install on a system that's desperately needed that refresh for a few years now but I have enough stuff installed on it that I haven't wanted to set aside all the time I would need to really do that.)

**Comment by BBC-Esq** [comment]
Sounds like you have a lot going on.  ;-)  Let me know if you eventually test your workaround, otherwise, I'll close this out in a few weeks unless there's an influx of other people interested in this issue, that is...

**Comment by zarlor** [comment]
Well, you do have TheRealBeef also interested, but if just the 2 of us is not enough I understand, although I do think it would be a worthwhile feature to consider. That being said I'm currently messing with GPT4All since that seems to be running with document integration relatively well on my system as is. It does lack some features of LM Studio, but it gets me going with what I need for now, at least.

**Comment by BBC-Esq** [comment]
OK...maybe I didn't quite understand what you're trying to achieve.  Believe it or not, I'm not a programmer by trade (am in the legal profession) and this is a hobby so...Can you explain a little more?  Basically, you want to be able to run LM Studio in server mode, and then use my program to connect to LM Studio, even if it's not on the same computer (but still on the same network...or are you wanting to connect somehow even if you're not on the same network...like remotely?

**Comment by zarlor** [comment]
Hey, I'm a computer geek, but not a coder so I completely get it, plus my use case is pushing things at least a little bit for an LLM (using your plugin to manage PDFs of rules and a campaign for an RPG, along with things like session recaps to use it to help me track things the PCs have done). But, yes, you've got it right, really just running LM Studio in server mode on a robust desktop (in the other room, but it also means more resources for LM Studio and potentially a stronger model because of that) while running your plugin on a laptop in the other room (on the same network) just pointing to the IP of the other computer instead of "localhost". 

If your plugin only needs to connect to LM Studio via port 1234 (I think it is, without checking the docs?) then it largely shouldn't matter if its on the same network or not, though, since it would just be connecting to whatever IP you give it (admittedly there may be other concerns with having the right firewall rules and the like in place, although I wouldn't think your program needs it). The network layer does provide a potential bottleneck over using the local loopback port, of course, but I wouldn't think it would be too terrible, but I also don't know how much traffic you need to shove between the database and LMM Studio, so...

**Comment by BBC-Esq** [comment]
Lol, I didn't understand anything you said except the end where you asked about how much data is sent from my program to LM Studio.  That's how little I know about networking.  ;-)  Th data my program sends is very little, it's a user's question plus however many "contexts" a user sends (multiplied by the chunk size)...And the only thing it receives is the LLM's response...And both are just a bunch of text so, it's basically nothing.

**Comment by zarlor** [comment]
Lol, ok, well how about this... your question was "Basically, you want to be able to run LM Studio in server mode, and then use my program to connect to LM Studio, even if it's not on the same computer (but still on the same network)?" to which I respond... Yes! :D

**Comment by BBC-Esq** [comment]
Aha!  I understand!  Let me ask Chat GPT4, brb.

**Comment by BBC-Esq** [comment]
[https://chat.openai.com/share/1ec18027-cfce-4e97-8330-1f5ecc00069e](https://chat.openai.com/share/1ec18027-cfce-4e97-8330-1f5ecc00069e)  Interesting idea, but I don't think I'll have time to work on it myself...

**Comment by BBC-Esq** [comment]
Closing for lack of help.

**Comment by zarlor** [comment]
Finally got to the point where I re-imaged my desktop (on Linux this time!) and set it up with LMStudio. Then on my laptop I now have your Plugin running and I did what I mentioned above, edited the src/config.yaml file and changed the entry for connection_str  from "localhost" to the IP of my Desktop and it works just fine! There are same network connections, mind you (as in 192.168 IPs) but it should work fine outside of that. Just wanted to post for anyone that happens to search for a similar use case.

I suppose really this feature request, then, would just be to add a field for that onto the Settings page right there along with being able to change the port. But, yeah, works just fine in case you ever needed to know. :)

**Comment by BBC-Esq** [comment]
That's interesting.  So remind me again, you're connecting to it on the same network but from a different computer?  So you just changed which part of the config.yaml?

**Comment by zarlor** [comment]
In the src/config.yaml file there is a line that says:

 connection_str: http://localhost:1234/v1
 
 I changed the "localhost" part to the IP of the other machine. Should work local or not, actually, so arguably it could be used to connect to, say, ChatGPT if you also provided an API key for it. Presumably your entry for the port to use just changes that line, at a guess (if not in the file then in memory, I suppose). Arguably it could be even more flexible by just allowing modification of that entire entry (for an API that doesn't use /v1, example, but that's getting deep into API weeds) and adding an API key. I guess the only issue then is more one of aesthetics since the program uses half of the real estate, so to speak, of its window on the configuration side of the box leaving less room for the main function, the chat stuff. Plus the chat is only ever sent by clicking the send button where it would be nice to use just Enter to send (and just use Shift-Enter to just do a new line when typing if needed),

**Comment by BBC-Esq** [comment]
You are correct, my program allows a user to alter the port number portion of that key in the config.yaml file only, not the entire line.  So it appears that you've manually modified the config.yaml and the entire line.  And yes, in theory it wouldn't be hard to connect to OpenAI's chat-gpt by providing a key in my script as well...feel free to modify and play with it.

So your other suggestions are make "enter" also submit the question and make the left portion collapsable perhaps...such that a user can click something to make the rightframe fill the entire gui?

**Comment by zarlor** [comment]
Pretty much, that's it. :) Those are just nice-to-have features having played around with some of the other chat-client options around.
