### ISSUE TITLE
Error: %EmbeddingModelDirectory% does not appear to have a file named config.json

### ISSUE THREAD

**Issue by mattwood2855** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#54]
File "D:\Repositories\ChromaDB-Plugin-for-LM-Studio-2.7.3\src\Lib\site-packages\transformers\utils\hub.py", line 360, in cached_file
    raise EnvironmentError(
OSError: D:/Repositories/ChromaDB-Plugin-for-LM-Studio-2.7.3/src/Embedding_Models/EmbeddingModelDir does not appear to have a file named config.json. Checkout 'https://huggingface.co/D:/Repositories/ChromaDB-Plugin-for-LM-Studio-2.7.3/src/Embedding_Models/EmbeddingModelDir/None' for available files.

**Comment by BBC-Esq** [comment]
You closed this issue out...did you find the solution?  Typically when users get something like this it's because all the embedding model files weren't downloaded before they tried to use it.  I recommend deleting everything and re-downloading if that's the case.

**Comment by mattwood2855** [comment]
It was a case of dumb user. I misinterpreted the instructions and was not selecting the directory where the models were being downloaded. I made a new dir and selected it thinking that was something would be placed there, not pulled from there.

Updating the selected directory fixed the issue
