### ISSUE TITLE
flash attention 2 support

### ISSUE THREAD

**Issue by BBC-Esq** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#56]
Flash attention 2 requires CUDA 12.1.  Ctranslate2 is in the process of building for CUDA 12.1...Since the transcription/file transcriber portion of the program uses ctranslate2, it should be prime time soon to upgrade to CUDA 12.1 and flash attention.

Flash attention 2 would be great for:

Greatly improving the Bark models' test to voice, speaking the LLM's response!
Greatly improving the vision model's (to be includes soon) performance within the program!
To the extent it becomes compatible, improve embedding models' performance.

**Comment by clickclack777** [comment]
Could also be used for transcription: 
https://github.com/Vaibhavs10/insanely-fast-whisper?tab=readme-ov-file

Add option to run on Apple Silicon :)

**Comment by BBC-Esq** [comment]
Yep, I'm familiar.  It would require abandoning the faster-whisper library though, which I'm not yet read to do.  I'm aware of it though...Plus faster-whisper supports more backends I believe.

**Comment by BBC-Esq** [comment]
Ready to implement...just a matter of faster-whisper becoming CUDA 12+ compatible out of the box.
