### ISSUE TITLE
"QPainter::end: Painter ended with 4 saved states" - repeated in command prompt

### ISSUE THREAD

**Issue by BBC-Esq** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#57]
Somehow this message is displayed, don't think it was a contribution I made...

```doh set to ""  --  SystemOnly```

I think someone is making a prank in my code by setting the variable "doh" to nothing everytime it loads...nicely done sir...

**Comment by gramss** [comment]
The 🃏 is your (floating) dependency stack.
It's every software stack's nightmare in a nutshell..

![](https://imgs.xkcd.com/comics/data_pipeline_2x.png)
(no rant at all. It's just what you get when using a lot of dependencies - btw I am amazed that this works all locally on my machine. Don't get me wrong at all..! 🚀 )


See this [StackOverflow Post](https://stackoverflow.com/questions/77337521/qwebengineview-in-pyside6-not-loading-any-page) regarding `doh`.

This is the explanation for the `doh`:
```
This enum sets the DNS-over-HTTPS mode used by the DnsMode structure:
+
+    \value SystemOnly This is the default. Use the system DNS host resolution.
+    \value SecureWithFallback Enable DNS-over-HTTPS (DoH). DoH servers have to be
+    provided through \l {QWebEngineGlobalSettings::DnsMode::serverTemplates}{serverTemplates} in
+    the DnsMode structure. If a host cannot be resolved via the provided servers,
+    the system DNS host resolution is used.
+    \value SecureOnly Enable DNS-over-HTTPS and only allow hosts to be resolved
+    this way. DoH servers have to be provided through
+    \l {QWebEngineGlobalSettings::DnsMode::serverTemplates}{serverTemplates} in the DnsMode
+    structure. If the DNS-over-HTTPS resolution fails, there is no fallback and the DNS host
+    resolution fails completely.

``` 

it is a debug message that is displayed always when using network. To me this is a bug in QT.:
```
 -113,8 +127,9 @@ void QWebEngineGlobalSettingsPrivate::configureStubHostResolver()
         network::mojom::NetworkService *networkService = content::GetNetworkService();
         if (networkService) {
             qDebug() << "doh set to" << dnsOverHttpsTemplates << " -- "
-                     << (dnsMode == QWebEngineGlobalSettings::DnsMode::SecureOnly ? "SecureOnly"
-                                 : dnsMode == QWebEngineGlobalSettings::DnsMode::SystemOnly
+                     << (dnsMode == QWebEngineGlobalSettings::SecureDnsMode::SecureOnly
+                                 ? "SecureOnly"
+                                 : dnsMode == QWebEngineGlobalSettings::SecureDnsMode::SystemOnly
                                  ? "SystemOnly"
                                  : "SecureWithFallback");
             absl::optional<net::DnsOverHttpsConfig> dohConfig = dnsOverHttpsTemplates.empty()
```
[source of the code snippet](https://code.qt.io/cgit/qt/qtwebengine.git/commit/?id=09e224c57c085457dbc5c2896aacb868a19c2ce6)

---

Same level of bug as these quadrupled messages once I context switch the GUI app: ```QPainter::end: Painter ended with 4 saved states ```


<details>
<summary>Hint on "fixing" this:</summary> 
Think about leaving QT behind. This also shoots you in the foot once somebody else or you want to use this software commercially regarding OSS licensing. But there is not "the one solution", always a specific decision with different complications one simply needs to be aware about.
</details>

**Comment by BBC-Esq** [comment]
Thanks for the message regarding qpainter.  I'm not getting that message, although you're the second or third person who's mentioned it.  I first heard of it approximately 2 months ago, but I can't replicate and hence can't troubleshoot.  I did some basic research and it has something to do with how the widgets are being painted, possibly exacerbated by how I'm laying out the widgets in my specific scripts.  The only thing that comes to mind is, within ```gui.py```, at the end where it says ```    app.setStyle(QStyleFactory.create('fusion'))```.  This tells my program to use the "fusion" style, which is basically a prebuilt style for all widgets, fonts, etc. that looks contemporary.  However, this caused problems with some mac users...I subsequently implemented custom style sheets, but I kept the fusion for those parts where CSS doesn't specify.  This way, I never get the default pyside6 coloring...it's either my CSS or, if not specified, fusion.

This is the only thing I can think of...

Try deleting the fusion style from the script altogether and see if you get the same error...I highly doubt it's how I organized my widgets.  I used them fairly conventionally so I think...so this'd be my best guess.

**Comment by BBC-Esq** [comment]
Aha!  I was finally able to reproduce it.  It occurred when the GUI was on another monitor and I minimized and retracted it to the task bar.  This did not occur on my main monitor.  Can anyone confirm something similar?

**Comment by BBC-Esq** [comment]
Finally able to reproduce and confirm that it's because "fusion" is used at the bottom of ```gui.py``` while at the same time controlling widgets through CSS.  Will likely expand CSS to mimic "fusion" to the extent possible even though it can't mimic everything, and then abandon fusion to avoid this message entirely.
