### ISSUE TITLE
Fail to recognise existing Docs_for_DB folder

### ISSUE THREAD

**Issue by clickclack777** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#58]
1. I´ve selected and downloaded the embedding model with confirmation in terminal that download is complete.
2. Chosen the folder "sentence-transformers--all-mpnet-base-v2" under "Embeding models" (only model I´ve downloaded).
3. Chosen the json files I want to embed. Checked that the symlinks are in the "/Users/click/ChromaLM/src/Docs_for_DB" folder.
4. When creating vector database I´m getting this error message in terminal:

FileNotFoundError: [Errno 2] No such file or directory: 'xdg-open "/Users/click/ChromaLM/src/Docs_for_DB"'

**Comment by BBC-Esq** [comment]
Solved by updating ```choose_documents.py``` to correctly open a folder depending on whether the OS is Windows, Linux or MacOS.
