### ISSUE TITLE
cuda 12.3 not detected on install of 2.7.5

### ISSUE THREAD

**Issue by Rotoslider** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#63]
I have cuda 12.3 nvida driver 545.92 in windows 10. Went to install ChromaDB 2.7.5 and it does not find Cuda. If i click cancel the ChromaDB installer keeps installing.

**Comment by BBC-Esq** [comment]
The program is not currently compatible with CUDA 12 but will be in the semi-near future.  This is due to the faster-whisper library not yet being compatible with it.
