### ISSUE TITLE
Installing/starting 3.0

### ISSUE THREAD

**Issue by clickclack777** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#67]
When starting 3.0, I received this traceback were the file path to were the pdf.py was missing in the SRC folder. I had to reacreate the entire path with empty folder until /parsers/ where I could place the pdf.py file. Doing so, enabled start of app.

----------------------------------------------------------------

Traceback (most recent call last):
  File "/Users/click/ChromaLM3/src/gui.py", line 288, in <module>
    ex = DocQA_GUI()
         ^^^^^^^^^^^
  File "/Users/click/ChromaLM3/src/gui.py", line 29, in __init__
    initialize_system()
  File "/Users/click/ChromaLM3/src/initialize.py", line 80, in main
    move_custom_pdf_loader()
  File "/Users/click/ChromaLM3/src/initialize.py", line 71, in move_custom_pdf_loader
    lib_pdf_size = lib_pdf_path.stat().st_size
                   ^^^^^^^^^^^^^^^^^^^
  File "/Users/click/miniforge3/envs/chromalm/lib/python3.11/pathlib.py", line 1013, in stat
    return os.stat(self, follow_symlinks=follow_symlinks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/click/ChromaLM3/src/Lib/site-packages/langchain/document_loaders/parsers/PDF.py'

**Comment by BBC-Esq** [comment]
Were you trying to run setup.py?

**Comment by BBC-Esq** [comment]
The newest release 3.0.2 is supposed to resolve any issues regarding this...

**Comment by clickclack777** [comment]
No, when starting the program with "python gui.py". It start the app but i get this:
qt.qpa.fonts: Populating font family aliases took 76 ms. Replace uses of missing font family "Segoe UI Historic" with one that exists to avoid this cost. 
doh set to ""  --  SystemOnly


When running "python setup.py" I get this:
Traceback (most recent call last):
  File "/Users/click/ChromaLM3/src/setup.py", line 86, in <module>
    setup_windows_installation()
  File "/Users/click/ChromaLM3/src/setup.py", line 62, in setup_windows_installation
    if not check_python_version_and_confirm():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/click/ChromaLM3/src/setup.py", line 19, in check_python_version_and_confirm
    return user_confirmation(f"Python version {sys.version.split()[0]} detected. Click OK to proceed with the installation, or Cancel to stop.")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/click/ChromaLM3/src/setup.py", line 8, in user_confirmation
    return ctypes.windll.user32.MessageBoxW(0, message, "Confirmation", 1) == 1
           ^^^^^^^^^^^^^
AttributeError: module 'ctypes' has no attribute 'windll'

**Comment by BBC-Esq** [comment]
If you are using Mac you're not supposed to be using setup.py...I see a line in the error that mentions that script.  Per the github instructions, setup.py is only for windows.

**Comment by BBC-Esq** [comment]
Basically, you need to move ```pdf.py``` to the langchain's "parsers" folder, which is within the "document_loaders" folder, and that path to it is different based on windows, linux or mac.  The new script in v3.0.2 is supposed to accurately search for the folder on non-windows machines and move the file if it hasn't been moved yet.

**Comment by clickclack777** [comment]
I didn´t run the setup.py until you mentioned in this thread. Just wanted to try out what happen, if I had missed some step in the setup of the new version. Great features in 3.0.2. Will try it/update out soon.

**Comment by BBC-Esq** [comment]
I'll close but let me know if you run into problems installing again.
