### ISSUE TITLE
ability to filter search results by metadata

### ISSUE THREAD

**Issue by clickclack777** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#68]
Would be great to be able to activate and deactivate different DB embeddings to submit questions to.

**Comment by BBC-Esq** [comment]
This pertains to the ability to create "collections," which in chromadb terminology, means different sets of documents all within the same database, and then being able to select a certain collection to search only.

The challenge is that, as far as I know, it means that all collections must be created with the same embedding model, although I could be wrong about this.  If true, however, it means that you couldn't add different collections to the database with different embeddings models...after all, different embedding models are better with certain kinds of documents.

With that being said, what kinds of documents would you use it for creating different collections?

There is already an approved feature request regarding being able to create multiple databases, which would achieve something similar.  Although you wouldn't be able to search a combination of databases (like being able to search multiple collections), you could search one database for PDF's for example, and another for EXCEL files.

Can you explain a little more what you're looking to do?

**Comment by clickclack777** [comment]
I was thinking that it would be useful if I had already created a embedding for one topic and wanted to combine that with another embedding with a different topic to look for similarities in-between the two. Since similarities is what vector DBs are good at. It would of-course also save creating embedding time and computation power for larger embeddings. I wouldn´t mind if it only worked in-between the same embedding model if that is what is possible. But it would also be cool to match a text embedding with an image embedding (if the image embeddings has the right metadata/tags). "Find matching images to chapter X by author X".

**Comment by BBC-Esq** [comment]
I'm changing this to add searchability by metadata because I think that's what you're getting at

**Comment by gramss** [comment]
Never heard of `vector DBs`, but what you are describing sounds a lot like knowledge graphs to me.
See this article for an explaination: [LinkedIn Article: "Knowledge Graphs as Fancy Databases"](https://www.linkedin.com/pulse/knowledge-graphs-fancy-databases-mike-dillinger-phd-fk8jc%3FtrackingId=pVH9TfBoSTyJ%252BJ2JIs0R%252Bg%253D%253D/?trackingId=pVH9TfBoSTyJ%2BJ2JIs0R%2Bg%3D%3D)
