### ISSUE TITLE
Graphical issues when resizing app window

### ISSUE THREAD

**Issue by clickclack777** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#70]
Graphical issues when resizing app window height on MacOS

![Screenshot 2023-12-28 at 21 08 26](https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio/assets/46272996/0061cc82-475a-4bc0-b5e4-22822a440f34)
![Screenshot 2023-12-28 at 21 08 42](https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio/assets/46272996/6da4e693-90ff-41e9-a8c5-1b3599eeccb6)
![Screenshot 2023-12-28 at 21 11 16](https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio/assets/46272996/68c8060f-0291-493f-8a3e-4a0bc1174f82)

**Comment by BBC-Esq** [comment]
Thank you for the screenshots.  Can we do a screenshare sometime?  DM me on the discord if you have time so we can troubleshoot.  I've never seen this behavior before and can't replicate it myself...

**Comment by clickclack777** [comment]
Yes, reached out and hour ago for a screenshare. I´m off a couple of days. Back on monday.

**Comment by BBC-Esq** [comment]
Didn't see it...but hit me up another time!

**Comment by lonebug11** [comment]
This also happens on Windows.

**Comment by lonebug11** [comment]
Unable to screenshare, but here is a picture from the latest release. (Happens when you drag resize)
![python_pzs9j2SgnI](https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio/assets/109964696/3cb03155-ee4d-460d-bcba-5a444bb20dec)

**Comment by BBC-Esq** [comment]
The resizing is actually how it's supposed to work, I've prioritized the lower settings boxes over the server/llm one, so when a user resizes that one compacts first.  the program is intended to be run with enough height so it doens't do that.  Also, if you never modify a setting, you can simply uncheck one of the boxes and that gives additional space to the others...
