### ISSUE TITLE
Plugin addon for LM Studio (co-lab)

### ISSUE THREAD

**Issue by clickclack777** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#71]
Colab with LM Studio to use your plugin as the DB tool to chat with docs in LM. That would be sick!

**Comment by BBC-Esq** [comment]
Sounds good but unfortunately I don't have the knowledge to do this since I don't use colab...and won't have a need.  If someone submits a pull request or takes this one though I'd be willing.  I'll leave this open for a bit.

**Comment by clickclack777** [comment]
I didn´t mean colab as in Google colab, meant a collaboration in-between the two of you. :)

**Comment by clickclack777** [comment]
I will add a feature request with your contact details on the LM Studio discord to get a response from them if you don´t mind.

**Comment by BBC-Esq** [comment]
Oh, it's a separate project and the developer of LM Studio hasn't expressed any interest in working with me so...Last I heard months ago was that he was developing his own vector database component...I wouldn't mind working "with" him but that's something he and I would have to discuss, feel free to mention it if you want, but he's expressed no interest.

**Comment by clickclack777** [comment]
OK, I see.

**Comment by BBC-Esq** [comment]
You could totally message him if you want.  I'm not comfortable messaging him because he's expressed no interest.  But please don't post anything with my details asking him to collaborate, but there's no harm in asking him.

**Comment by clickclack777** [comment]
OK, no worries. I´ve just expressed the desire for a colab since I found a thread on their discord that has 55 upvotes in regards to this with someone else suggesting an integration with your plug-in.

**Comment by clickclack777** [comment]
Would your plugin work as an extension of Langchain instead of the regular ChromaDB? Haven´t dived into Langchain yet.

**Comment by BBC-Esq** [comment]
Do you have the link to where someone else suggested integrating?

**Comment by clickclack777** [comment]
https://discord.com/channels/1110598183144399058/1179311890334220329

**Comment by clickclack777** [comment]
Would it be difficult to add LLM model selection and chat with https://ollama.ai/ to your app?

**Comment by BBC-Esq** [comment]
Don't know what that is but I can take a look.

**Comment by clickclack777** [comment]
It´s an LLM chat client for the terminal where you can basically do the things you do in LM studio. User experience is more primitive since everything is through the terminal and commands. 

Then you have this unaffiliated UI that turns Ollama into a ChatGPT client in the browser which is nice. 
https://github.com/ollama-webui/ollama-webui?tab=readme-ov-file

Would be sick to have your plugin running on a local computer and accessing it though a remote browser with sign-in.

**Comment by clickclack777** [comment]
https://discord.com/channels/1110598183144399058/1189492712471285831
