### ISSUE TITLE
Feature Request: Additional filetypes

### ISSUE THREAD

**Issue by lonebug11** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#72]
Will there be an additional support for more file types on the langchain processing part?

**Comment by BBC-Esq** [comment]
Which files types?  You can go here and pick some out that you think would be useful.  Look under the "loaders" portion: [https://integrations.langchain.com/](https://integrations.langchain.com/)

**Comment by lonebug11** [comment]
I would like to see the ability to import html files, to store data taken from websites as well as markdown pages from documentation such as .md

UnstructuredHTMLLoader
UnstructuredMarkdownLoader

This would be the primary use-cases for me at the moment, perhaps you can expand on the project making it user friendly to extend the file extensions in the future.

**Comment by BBC-Esq** [comment]
I can update it to support HTML but I don't use it or that.  Let me know.  Will upload in about 10 minutes.  Just replace your current ```document_processor.py``` script with the newest one on the repo...there won't be a separate release for this.

**Comment by BBC-Esq** [comment]
Markdown was already incorporated but there was a bug...fixed now so .html, .htm, and .md should all work now.  you'll need to download ```choose_documents.py```, ```constants.py```, and ```document_processor.py``` and replace the ones you have with those.
