### ISSUE TITLE
Minimum System Requirements?

### ISSUE THREAD

**Issue by shiloh92** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#78]
Just a simple add on to the readme would be - 

VRAM suggested for each module - Bare Minimum System Requirements for All Modules to Work

-  TTS(?)
- Vision(I don't know of any that takes less than XXGB of VRAM), I only know of Llava so far and I'm sure it's hefty
- LLM (varies of course)

I'd like to try this plugin but I'm not sure it's worth setting up if my system cannot run it.

**Comment by BBC-Esq** [comment]
Awhile back I was thinking of perhaps some kind of calculator...e.g. a user selects a model, it updates with the estimated vram in the GUI needed...they change the quantization...it automatically updates in a little box the "estimated vram" needed etc.
