### ISSUE TITLE
no Docs_for_DB folder prevents images from being processed

### ISSUE THREAD

**Issue by BBC-Esq** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#80]
Bug only occurs if you've never created a database with non-images before and you first select images only to create the database with.  It will throw an error saying it can't find the "docs_for_db" folder.  This is because it only creates the "Docs_for_DB" folder when you select a non-image.  This occurs because the scripts automatically create the folder when selecting non-image docs.

Need to change it so if a user selects only images without ever first creating a database with non-images, it creates both Docs_for_DB as well as Images_for_DB and vice versa.

**Comment by cddigi** [comment]
should be fixed with https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio/pull/76
