### ISSUE TITLE
Issues creating vector DB under Linux

### ISSUE THREAD

**Issue by digiantnz** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#84]
Creating a new vector DB and it errors with 'safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge'

Using BAAI/bge-small-en-v.15

Terminal output

<pre>Selected directory: /home/thesteamyuser/Documents/ChromaDB-Plugin-for-LM-Studio-3.0.2/src/Embedding_Models/BAAI--bge-small-en-v1.5
<font color="#EEEEEC">create_database.py: Loading documents.</font>
<font color="#EEEEEC">document_processor.py: Number of workers assigned: 1</font>
<font color="#C4A000">document_processor.py: Number of NON-IMAGE files loaded: 1</font>
<font color="#C4A000">document_processor.py: Loading images, if any.</font>
No files detected in the &apos;Images_for_DB&apos; directory.
<font color="#EEEEEC">create_database.py: Successfully loaded documents.</font>
<font color="#EEEEEC">document_processor.py: Splitting documents.</font>
<font color="#EEEEEC">document_processor.py: Number of Chunks: 7781</font>
<font color="#EEEEEC">document_processor.py: Chunks between 1 and 100 characters: 47</font>
<font color="#EEEEEC">document_processor.py: Chunks between 101 and 200 characters: 48</font>
<font color="#EEEEEC">document_processor.py: Chunks between 201 and 300 characters: 177</font>
<font color="#EEEEEC">document_processor.py: Chunks between 301 and 400 characters: 224</font>
<font color="#EEEEEC">document_processor.py: Chunks between 401 and 500 characters: 302</font>
<font color="#EEEEEC">document_processor.py: Chunks between 501 and 600 characters: 584</font>
<font color="#EEEEEC">document_processor.py: Chunks between 601 and 700 characters: 1359</font>
<font color="#EEEEEC">document_processor.py: Chunks between 701 and 800 characters: 5040</font>
<font color="#EEEEEC">create_database.py: Creating embeddings.</font>
Traceback (most recent call last):
  File &quot;/home/thesteamyuser/Documents/ChromaDB-Plugin-for-LM-Studio-3.0.2/src/gui_threads.py&quot;, line 7, in run
    create_database.main()
  File &quot;/home/thesteamyuser/Documents/ChromaDB-Plugin-for-LM-Studio-3.0.2/src/create_database.py&quot;, line 46, in main
    embeddings = get_embeddings(EMBEDDING_MODEL_NAME, config_data)
  File &quot;/home/thesteamyuser/Documents/ChromaDB-Plugin-for-LM-Studio-3.0.2/src/create_database.py&quot;, line 91, in get_embeddings
    return HuggingFaceBgeEmbeddings(
  File &quot;/home/thesteamyuser/.local/lib/python3.10/site-packages/langchain/embeddings/huggingface.py&quot;, line 232, in __init__
    self.client = sentence_transformers.SentenceTransformer(
  File &quot;/home/thesteamyuser/.local/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py&quot;, line 95, in __init__
    modules = self._load_sbert_model(model_path)
  File &quot;/home/thesteamyuser/.local/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py&quot;, line 840, in _load_sbert_model
    module = module_class.load(os.path.join(model_path, module_config[&apos;path&apos;]))
  File &quot;/home/thesteamyuser/.local/lib/python3.10/site-packages/sentence_transformers/models/Transformer.py&quot;, line 137, in load
    return Transformer(model_name_or_path=input_path, **config)
  File &quot;/home/thesteamyuser/.local/lib/python3.10/site-packages/sentence_transformers/models/Transformer.py&quot;, line 29, in __init__
    self._load_model(model_name_or_path, config, cache_dir)
  File &quot;/home/thesteamyuser/.local/lib/python3.10/site-packages/sentence_transformers/models/Transformer.py&quot;, line 49, in _load_model
    self.auto_model = AutoModel.from_pretrained(model_name_or_path, config=config, cache_dir=cache_dir)
  File &quot;/home/thesteamyuser/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py&quot;, line 566, in from_pretrained
    return model_class.from_pretrained(
  File &quot;/home/thesteamyuser/.local/lib/python3.10/site-packages/transformers/modeling_utils.py&quot;, line 3359, in from_pretrained
    with safe_open(resolved_archive_file, framework=&quot;pt&quot;) as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
</pre>

**Comment by digiantnz** [comment]
The txt file in question
[Oxford English Dictionary.txt](https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio/files/13806417/Oxford.English.Dictionary.txt)

**Comment by BBC-Esq** [comment]
Thanks, and maybe a redundant question, but you're following the instructions on the github to a "T" is that right?

**Comment by BBC-Esq** [comment]
Confirmed that the embeddings were created of the .txt file after approximately 8 seconds...used all-mpnet embedding model, chunk size 400, overlap 100, rtx 4090, cuda compute device.

Afterwards, saving the database to disk took almost 20 seconds, which is within the range of normal.
Unable to duplicate the error...GPT-4 says that it could be a mismatch of one or more of the library versions that you have...

Can you do "pip list" and show the results here?  Must be within the virtual environment of course...

**Comment by digiantnz** [comment]
Yep (admittedly I haven't made it *that* far yet) . python3 check_gpu.py reports

![image](https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio/assets/89875136/0db24f9b-8216-4324-ab72-753da37cdb52)


Also tried the BAAI/bge-large-en-v.15 but go the same error

**Comment by BBC-Esq** [comment]
I skimmed the beginning of the error...it quotes lines 46 and 91 of ```create_database.py``` yet those lines don't match with my version that I have marked as the v3.0.3 version.  Can you confirm that you're only using the files from the "release" v3.0.3?

**Comment by digiantnz** [comment]
<pre>ackage                  Version
------------------------ ----------------
accelerate               0.25.0
aiohttp                  3.9.1
aiosignal                1.3.1
anyio                    3.7.1
async-timeout            4.0.3
attrs                    23.2.0
av                       10.0.0
backoff                  2.2.1
bcc                      0.18.0
beautifulsoup4           4.12.2
bitsandbytes             0.41.3.post2
blinker                  1.4
Brlapi                   0.8.3
certifi                  2023.11.17
chardet                  4.0.0
charset-normalizer       3.3.2
chromadb                 0.3.29
chrome-gnome-shell       0.0.0
click                    8.0.3
clickhouse-connect       0.6.23
colorama                 0.4.4
coloredlogs              15.0.1
command-not-found        0.3
cryptography             3.4.8
ctranslate2              3.23.0
cupshelpers              1.0
dataclasses-json         0.6.3
datasets                 2.16.1
dbus-python              1.2.18
defer                    1.0.6
dill                     0.3.7
distro                   1.7.0
docx2txt                 0.8
duckdb                   0.9.2
einops                   0.7.0
emoji                    2.9.0
et-xmlfile               1.1.0
evdev                    1.4.0
exceptiongroup           1.2.0
fastapi                  0.85.1
faster-whisper           0.10.0
filelock                 3.13.1
filetype                 1.2.0
flatbuffers              23.5.26
frozenlist               1.4.1
fsspec                   2023.10.0
greenlet                 3.0.3
h11                      0.14.0
hidpidaemon              18.4.6
hnswlib                  0.8.0
httplib2                 0.20.2
httptools                0.6.1
huggingface-hub          0.20.1
humanfriendly            10.0
idna                     3.6
importlib-metadata       4.6.4
InstructorEmbedding      1.0.1
jeepney                  0.7.1
Jinja2                   3.1.2
joblib                   1.3.2
jsonpatch                1.33
jsonpath-python          1.0.6
jsonpointer              2.4
kernelstub               3.1.4
keyring                  23.5.0
langchain                0.0.341
langchain-core           0.0.6
langdetect               1.0.9
langsmith                0.0.75
language-selector        0.1
launchpadlib             1.10.16
lazr.restfulclient       0.14.4
lazr.uri                 1.0.6
louis                    3.20.0
lxml                     5.0.0
lz4                      4.3.2
macaroonbakery           1.3.1
MarkupSafe               2.1.3
marshmallow              3.20.1
meson                    0.61.2
monotonic                1.6
more-itertools           8.10.0
mpmath                   1.3.0
msg-parser               1.2.0
multidict                6.0.4
multiprocess             0.70.15
mypy-extensions          1.0.0
netaddr                  0.8.0
netifaces                0.11.0
networkx                 3.2.1
nltk                     3.8.1
numpy                    1.26.2
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        8.9.2.26
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-ml-py             12.535.108
nvidia-nccl-cu12         2.18.1
nvidia-nvjitlink-cu12    12.3.101
nvidia-nvtx-cu12         12.1.105
oauthlib                 3.2.0
olefile                  0.46
onnxruntime              1.16.3
openai                   0.28.0
openpyxl                 3.1.2
optimum                  1.15.0
overrides                7.4.0
packaging                23.2
pandas                   2.0.3
Pillow                   9.0.1
pip                      22.0.2
pop-transition           1.1.2
posthog                  3.1.0
protobuf                 3.12.4
psutil                   5.9.5
pulsar-client            3.3.0
pyarrow                  14.0.2
pyarrow-hotfix           0.6
PyAudio                  0.2.14
pycairo                  1.20.1
pycryptodomex            3.11.0
pycups                   2.0.1
pydantic                 1.10.13
pydbus                   0.6.0
PyGObject                3.42.1
PyJWT                    2.3.0
pymacaroons              0.13.0
PyMuPDF                  1.23.7
PyMuPDFb                 1.23.7
PyNaCl                   1.5.0
pypandoc                 1.12
pyparsing                2.4.7
pyRFC3339                1.1
PySide6                  6.6.1
PySide6-Addons           6.6.1
PySide6-Essentials       6.6.1
python-apt               2.4.0+ubuntu2
python-dateutil          2.8.2
python-debian            0.1.43+ubuntu1.1
python-docx              1.1.0
python-dotenv            1.0.0
python-gnupg             0.4.8
python-iso639            2023.12.11
python-magic             0.4.27
python-xlib              0.29
pytz                     2022.1
pyudev                   0.22.0
pyxdg                    0.27
PyYAML                   6.0.1
rapidfuzz                3.6.1
regex                    2023.12.25
repolib                  2.2.1
repoman                  1.4.0
requests                 2.31.0
safetensors              0.4.1
scikit-learn             1.3.2
scipy                    1.11.4
screen-resolution-extra  0.0.0
SecretStorage            3.3.1
sentence-transformers    2.2.2
sentencepiece            0.1.99
sessioninstaller         0.0.0
setuptools               59.6.0
shiboken6                6.6.1
six                      1.16.0
sniffio                  1.3.0
soupsieve                2.5
SQLAlchemy               2.0.24
starlette                0.20.4
sympy                    1.12
systemd-python           234
tabulate                 0.9.0
tenacity                 8.2.3
termcolor                2.3.0
threadpoolctl            3.2.0
tokenizers               0.15.0
torch                    2.1.2
torchvision              0.16.2
tqdm                     4.66.1
transformers             4.36.0
triton                   2.1.0
typing_extensions        4.9.0
typing-inspect           0.9.0
tzdata                   2023.4
ubuntu-advantage-tools   8001
ubuntu-drivers-common    0.0.0
ufw                      0.36.1
unstructured             0.11.6
unstructured-client      0.15.1
urllib3                  2.1.0
uvicorn                  0.25.0
uvloop                   0.19.0
wadllib                  1.3.6
watchfiles               0.21.0
websockets               12.0
wheel                    0.37.1
wrapt                    1.16.0
xdg                      5
xkit                     0.0.0
xlrd                     2.0.1
xxhash                   3.4.1
yarl                     1.9.4
zipp                     1.0.0
zstandard                0.22.0
</pre>

**Comment by BBC-Esq** [comment]
![image](https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio/assets/108230321/dc0716db-deef-476e-ad37-52cd8c09566b)
and see this...
![image](https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio/assets/108230321/3f5981a6-8b2a-43c8-bd27-08d9839d287c)

**Comment by digiantnz** [comment]
> I skimmed the beginning of the error...it quotes lines 46 and 91 of `create_database.py` yet those lines don't match with my version that I have marked as the v3.0.3 version. Can you confirm that you're only using the files from the "release" v3.0.3?

Aha! Mine says 3.0.2

**Comment by BBC-Esq** [comment]
(sound or forehead hitting desk...)  j/k man.  ;-)

**Comment by BBC-Esq** [comment]
In all fairness...I have been issuing releases like a spastic teenager hopped up on Mountain Dew so...it's perhaps understandable.

**Comment by BBC-Esq** [comment]
This is just a first glance as well...but I noticed that you're using CUDA 12?  The program is only compatible with CUDA 11.8 currently...but should be 12+ compatible soon.  Waiting on one dependency to upgrade...

**Comment by BBC-Esq** [comment]
> Yep (admittedly I haven't made it _that_ far yet) . python3 check_gpu.py reports
> 
> ![image](https://private-user-images.githubusercontent.com/89875136/293612634-0db24f9b-8216-4324-ab72-753da37cdb52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNTU3NjcsIm5iZiI6MTcwNDE1NTQ2NywicGF0aCI6Ii84OTg3NTEzNi8yOTM2MTI2MzQtMGRiMjRmOWItODIxNi00MzI0LWFiNzItNzUzZGEzN2NkYjUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDAwMzEwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1ZjU4NTU1ZGI1ZDg1MjczYjdjMzY2YWQ4ZWE1OTZmYjMxMzc1MTg3ODk1OWU2MTExNzhmZGUwMDJiNzliZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K7eSkAWC3DW2XRMZdaSxF7uVoyeo6dKljj5SjD8FKmo)
> 
> Also tried the BAAI/bge-large-en-v.15 but go the same error

And I just noticed it says CUDA 12 so...see above regarding 11.8.

**Comment by digiantnz** [comment]
> This is just a first glance as well...but I noticed that you're using CUDA 12? The program is only compatible with CUDA 11.8 currently...but should be 12+ compatible soon. Waiting on one dependency to upgrade...

Ahhh OK this could be a thing. Looks like I have to wait for your next mountain dew V12 inspired release

**Comment by digiantnz** [comment]
Same issue in 3.0.3

<pre>doh set to &quot;&quot;  --  SystemOnly
config.yaml file updated
Cloning into &apos;Embedding_Models/BAAI--bge-large-en-v1.5&apos;...
remote: Enumerating objects: 45, done.
remote: Total 45 (delta 0), reused 0 (delta 0), pack-reused 45
Unpacking objects: 100% (45/45), 345.67 KiB | 570.00 KiB/s, done.
BAAI/bge-large-en-v1.5 has been downloaded and is ready to use!
Selected directory: /home/thesteamyuser/Documents/ChromaDB-Plugin-for-LM-Studio-3.0.3/src/Embedding_Models/BAAI--bge-large-en-v1.5
<font color="#EEEEEC">create_database.py: Loading documents.</font>
<font color="#EEEEEC">document_processor.py: Number of workers assigned: 1</font>
<font color="#C4A000">document_processor.py: Number of NON-IMAGE files loaded: 1</font>
<font color="#C4A000">document_processor.py: Loading images, if any.</font>
No files detected in the &apos;Images_for_DB&apos; directory.
<font color="#EEEEEC">create_database.py: Successfully loaded documents.</font>
<font color="#EEEEEC">document_processor.py: Splitting documents.</font>
<font color="#EEEEEC">document_processor.py: Number of Chunks: 7781</font>
<font color="#EEEEEC">document_processor.py: Chunks between 1 and 100 characters: 47</font>
<font color="#EEEEEC">document_processor.py: Chunks between 101 and 200 characters: 48</font>
<font color="#EEEEEC">document_processor.py: Chunks between 201 and 300 characters: 177</font>
<font color="#EEEEEC">document_processor.py: Chunks between 301 and 400 characters: 224</font>
<font color="#EEEEEC">document_processor.py: Chunks between 401 and 500 characters: 302</font>
<font color="#EEEEEC">document_processor.py: Chunks between 501 and 600 characters: 584</font>
<font color="#EEEEEC">document_processor.py: Chunks between 601 and 700 characters: 1359</font>
<font color="#EEEEEC">document_processor.py: Chunks between 701 and 800 characters: 5040</font>
<font color="#EEEEEC">create_database.py: Creating embeddings.</font>
Traceback (most recent call last):
  File &quot;/home/thesteamyuser/Documents/ChromaDB-Plugin-for-LM-Studio-3.0.3/src/gui_threads.py&quot;, line 7, in run
    create_database.main()
  File &quot;/home/thesteamyuser/Documents/ChromaDB-Plugin-for-LM-Studio-3.0.3/src/create_database.py&quot;, line 49, in main
    embeddings = get_embeddings(EMBEDDING_MODEL_NAME, config_data)
  File &quot;/home/thesteamyuser/Documents/ChromaDB-Plugin-for-LM-Studio-3.0.3/src/create_database.py&quot;, line 94, in get_embeddings
    return HuggingFaceBgeEmbeddings(
  File &quot;/home/thesteamyuser/.local/lib/python3.10/site-packages/langchain/embeddings/huggingface.py&quot;, line 232, in __init__
    self.client = sentence_transformers.SentenceTransformer(
  File &quot;/home/thesteamyuser/.local/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py&quot;, line 95, in __init__
    modules = self._load_sbert_model(model_path)
  File &quot;/home/thesteamyuser/.local/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py&quot;, line 840, in _load_sbert_model
    module = module_class.load(os.path.join(model_path, module_config[&apos;path&apos;]))
  File &quot;/home/thesteamyuser/.local/lib/python3.10/site-packages/sentence_transformers/models/Transformer.py&quot;, line 137, in load
    return Transformer(model_name_or_path=input_path, **config)
  File &quot;/home/thesteamyuser/.local/lib/python3.10/site-packages/sentence_transformers/models/Transformer.py&quot;, line 29, in __init__
    self._load_model(model_name_or_path, config, cache_dir)
  File &quot;/home/thesteamyuser/.local/lib/python3.10/site-packages/sentence_transformers/models/Transformer.py&quot;, line 49, in _load_model
    self.auto_model = AutoModel.from_pretrained(model_name_or_path, config=config, cache_dir=cache_dir)
  File &quot;/home/thesteamyuser/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py&quot;, line 566, in from_pretrained
    return model_class.from_pretrained(
  File &quot;/home/thesteamyuser/.local/lib/python3.10/site-packages/transformers/modeling_utils.py&quot;, line 3359, in from_pretrained
    with safe_open(resolved_archive_file, framework=&quot;pt&quot;) as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge</pre>


but I am CUDA 12.1 confirmed 

![image](https://github.com/BBC-Esq/ChromaDB-Plugin-for-LM-Studio/assets/89875136/679461a6-ec40-45c3-9291-fcfcd0982b5e)

and downgrading might not be the best idea

**Comment by BBC-Esq** [comment]
Yeah, have you tried CUDA 11.8?  Unless you absolutely need 12+ it's a viable option, but up to you.  I'll mark this as under review for a little bit longer.

**Comment by digiantnz** [comment]
> Yeah, have you tried CUDA 11.8? Unless you absolutely need 12+ it's a viable option, but up to you. I'll mark this as under review for a little bit longer.

I had downloaded and installed 11.8 but given it had various PATH and bitsandbytes errors (including libcudart.so not found)  it may be better to stick with the package installer versions and wait for the updated plugin to confirm

**Comment by BBC-Esq** [comment]
Alright, I'll close this out then.

**Comment by digiantnz** [comment]
OK I've downgraded to 11.8, still has the issue though

<pre><font color="#3465A4"><b>/Documents/ChromaDB-Plugin-for-LM-Studio-3.0.3/src</b></font>$ python gui.py
doh set to &quot;&quot;  --  SystemOnly
Selected directory: /home/thesteamyuser/Documents/ChromaDB-Plugin-for-LM-Studio-3.0.3/src/Embedding_Models/BAAI--bge-large-en-v1.5
<font color="#EEEEEC">create_database.py: Loading documents.</font>
<font color="#EEEEEC">document_processor.py: Number of workers assigned: 1</font>
<font color="#C4A000">document_processor.py: Number of NON-IMAGE files loaded: 1</font>
<font color="#C4A000">document_processor.py: Loading images, if any.</font>
No files detected in the &apos;Images_for_DB&apos; directory.
<font color="#EEEEEC">create_database.py: Successfully loaded documents.</font>
<font color="#EEEEEC">document_processor.py: Splitting documents.</font>
<font color="#EEEEEC">document_processor.py: Number of Chunks: 7781</font>
<font color="#EEEEEC">document_processor.py: Chunks between 1 and 100 characters: 47</font>
<font color="#EEEEEC">document_processor.py: Chunks between 101 and 200 characters: 48</font>
<font color="#EEEEEC">document_processor.py: Chunks between 201 and 300 characters: 177</font>
<font color="#EEEEEC">document_processor.py: Chunks between 301 and 400 characters: 224</font>
<font color="#EEEEEC">document_processor.py: Chunks between 401 and 500 characters: 302</font>
<font color="#EEEEEC">document_processor.py: Chunks between 501 and 600 characters: 584</font>
<font color="#EEEEEC">document_processor.py: Chunks between 601 and 700 characters: 1359</font>
<font color="#EEEEEC">document_processor.py: Chunks between 701 and 800 characters: 5040</font>
<font color="#EEEEEC">create_database.py: Creating embeddings.</font>
Traceback (most recent call last):
  File &quot;/home/thesteamyuser/Documents/ChromaDB-Plugin-for-LM-Studio-3.0.3/src/gui_threads.py&quot;, line 7, in run
    create_database.main()
  File &quot;/home/thesteamyuser/Documents/ChromaDB-Plugin-for-LM-Studio-3.0.3/src/create_database.py&quot;, line 49, in main
    embeddings = get_embeddings(EMBEDDING_MODEL_NAME, config_data)
  File &quot;/home/thesteamyuser/Documents/ChromaDB-Plugin-for-LM-Studio-3.0.3/src/create_database.py&quot;, line 94, in get_embeddings
    return HuggingFaceBgeEmbeddings(
  File &quot;/home/thesteamyuser/Documents/ChromaDB-Plugin-for-LM-Studio-3.0.3/src/lib/python3.10/site-packages/langchain/embeddings/huggingface.py&quot;, line 232, in __init__
    self.client = sentence_transformers.SentenceTransformer(
  File &quot;/home/thesteamyuser/Documents/ChromaDB-Plugin-for-LM-Studio-3.0.3/src/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py&quot;, line 95, in __init__
    modules = self._load_sbert_model(model_path)
  File &quot;/home/thesteamyuser/Documents/ChromaDB-Plugin-for-LM-Studio-3.0.3/src/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py&quot;, line 840, in _load_sbert_model
    module = module_class.load(os.path.join(model_path, module_config[&apos;path&apos;]))
  File &quot;/home/thesteamyuser/Documents/ChromaDB-Plugin-for-LM-Studio-3.0.3/src/lib/python3.10/site-packages/sentence_transformers/models/Transformer.py&quot;, line 137, in load
    return Transformer(model_name_or_path=input_path, **config)
  File &quot;/home/thesteamyuser/Documents/ChromaDB-Plugin-for-LM-Studio-3.0.3/src/lib/python3.10/site-packages/sentence_transformers/models/Transformer.py&quot;, line 29, in __init__
    self._load_model(model_name_or_path, config, cache_dir)
  File &quot;/home/thesteamyuser/Documents/ChromaDB-Plugin-for-LM-Studio-3.0.3/src/lib/python3.10/site-packages/sentence_transformers/models/Transformer.py&quot;, line 49, in _load_model
    self.auto_model = AutoModel.from_pretrained(model_name_or_path, config=config, cache_dir=cache_dir)
  File &quot;/home/thesteamyuser/Documents/ChromaDB-Plugin-for-LM-Studio-3.0.3/src/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py&quot;, line 566, in from_pretrained
    return model_class.from_pretrained(
  File &quot;/home/thesteamyuser/Documents/ChromaDB-Plugin-for-LM-Studio-3.0.3/src/lib/python3.10/site-packages/transformers/modeling_utils.py&quot;, line 3359, in from_pretrained
    with safe_open(resolved_archive_file, framework=&quot;pt&quot;) as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge</pre>

**Comment by digiantnz** [comment]
so  downloaded hkunlp--instructor-xl but this was the output

<pre><font color="#EEEEEC">create_database.py: Loading documents.</font>
<font color="#EEEEEC">document_processor.py: Number of workers assigned: 1</font>
<font color="#C4A000">document_processor.py: Number of NON-IMAGE files loaded: 1</font>
<font color="#C4A000">document_processor.py: Loading images, if any.</font>
No files detected in the &apos;Images_for_DB&apos; directory.
<font color="#EEEEEC">create_database.py: Successfully loaded documents.</font>
<font color="#EEEEEC">document_processor.py: Splitting documents.</font>
<font color="#EEEEEC">document_processor.py: Number of Chunks: 7781</font>
<font color="#EEEEEC">document_processor.py: Chunks between 1 and 100 characters: 47</font>
<font color="#EEEEEC">document_processor.py: Chunks between 101 and 200 characters: 48</font>
<font color="#EEEEEC">document_processor.py: Chunks between 201 and 300 characters: 177</font>
<font color="#EEEEEC">document_processor.py: Chunks between 301 and 400 characters: 224</font>
<font color="#EEEEEC">document_processor.py: Chunks between 401 and 500 characters: 302</font>
<font color="#EEEEEC">document_processor.py: Chunks between 501 and 600 characters: 584</font>
<font color="#EEEEEC">document_processor.py: Chunks between 601 and 700 characters: 1359</font>
<font color="#EEEEEC">document_processor.py: Chunks between 701 and 800 characters: 5040</font>
<font color="#EEEEEC">create_database.py: Creating embeddings.</font>
load INSTRUCTOR_Transformer
Traceback (most recent call last):
  File &quot;/home/thesteamyuser/.local/lib/python3.10/site-packages/transformers/modeling_utils.py&quot;, line 519, in load_state_dict
    return torch.load(checkpoint_file, map_location=map_location)
  File &quot;/home/thesteamyuser/.local/lib/python3.10/site-packages/torch/serialization.py&quot;, line 1028, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File &quot;/home/thesteamyuser/.local/lib/python3.10/site-packages/torch/serialization.py&quot;, line 1246, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, &apos;v&apos;.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &quot;/home/thesteamyuser/Documents/ChromaDB-Plugin-for-LM-Studio-3.0.3/src/gui_threads.py&quot;, line 7, in run
    create_database.main()
  File &quot;/home/thesteamyuser/Documents/ChromaDB-Plugin-for-LM-Studio-3.0.3/src/create_database.py&quot;, line 49, in main
    embeddings = get_embeddings(EMBEDDING_MODEL_NAME, config_data)
  File &quot;/home/thesteamyuser/Documents/ChromaDB-Plugin-for-LM-Studio-3.0.3/src/create_database.py&quot;, line 83, in get_embeddings
    return HuggingFaceInstructEmbeddings(
  File &quot;/home/thesteamyuser/.local/lib/python3.10/site-packages/langchain/embeddings/huggingface.py&quot;, line 149, in __init__
    self.client = INSTRUCTOR(
  File &quot;/home/thesteamyuser/.local/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py&quot;, line 95, in __init__
    modules = self._load_sbert_model(model_path)
  File &quot;/home/thesteamyuser/.local/lib/python3.10/site-packages/InstructorEmbedding/instructor.py&quot;, line 474, in _load_sbert_model
    module = module_class.load(os.path.join(model_path, module_config[&apos;path&apos;]))
  File &quot;/home/thesteamyuser/.local/lib/python3.10/site-packages/InstructorEmbedding/instructor.py&quot;, line 306, in load
    return INSTRUCTOR_Transformer(model_name_or_path=input_path, **config)
  File &quot;/home/thesteamyuser/.local/lib/python3.10/site-packages/InstructorEmbedding/instructor.py&quot;, line 240, in __init__
    self._load_model(self.model_name_or_path, config, cache_dir, **model_args)
  File &quot;/home/thesteamyuser/.local/lib/python3.10/site-packages/sentence_transformers/models/Transformer.py&quot;, line 47, in _load_model
    self._load_t5_model(model_name_or_path, config, cache_dir)
  File &quot;/home/thesteamyuser/.local/lib/python3.10/site-packages/sentence_transformers/models/Transformer.py&quot;, line 55, in _load_t5_model
    self.auto_model = T5EncoderModel.from_pretrained(model_name_or_path, config=config, cache_dir=cache_dir)
  File &quot;/home/thesteamyuser/.local/lib/python3.10/site-packages/transformers/modeling_utils.py&quot;, line 3381, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File &quot;/home/thesteamyuser/.local/lib/python3.10/site-packages/transformers/modeling_utils.py&quot;, line 524, in load_state_dict
    raise OSError(
OSError: You seem to have cloned a repository without having git-lfs installed. Please install git-lfs and run `git lfs install` followed by `git lfs pull` in the folder you cloned.
</pre>

So which directory is missing git-lfs the src directory or the embeding model directory?
