### ISSUE TITLE
Error when creating vector embedding

### ISSUE THREAD

**Issue by clickclack777** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#91]
I´m getting this error when creating vector embedding .md files on MacOS - M1 silicon chip - Sonoma 14.2.1

    if platform.system() == "Darwin" and any(images_dir.iterdir()):
                                             ^^^^^^^^^^
    UnboundLocalError: cannot access local variable 'images_dir' where it is not associated with a value

Getting the same error for text files.

**Comment by BBC-Esq** [comment]
So it's just with .md and .txt files..?  Can you paste more details of the errors printed in the command prompt; for example, the full traceback history?

**Comment by clickclack777** [comment]
UnboundLocalError: cannot access local variable 'images_dir' where it is not associated with a value
Traceback (most recent call last):
  File "/Users/click/ChromaLM306/src/gui.py", line 148, in on_create_button_clicked
    if platform.system() == "Darwin" and any(images_dir.iterdir()):
                                             ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'images_dir' where it is not associated with a value

**Comment by BBC-Esq** [comment]
Try the newest release because I moved that button...

**Comment by clickclack777** [comment]
Alright, it worked with 3.1.1
