### ISSUE TITLE
Feature request: Add different retrieval types

### ISSUE THREAD

**Issue by clickclack777** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#92]
https://python.langchain.com/docs/modules/data_connection/retrievers/

**Comment by BBC-Esq** [comment]
I'm currently planning on being able to filter search by metadata.  I like this link you sent, however, it'd be a long time before I have any time to implement any of these features...

**Comment by clickclack777** [comment]
OK, no rush. Just wanted to let you know since it would expand core functionalities of the app.

**Comment by BBC-Esq** [comment]
I mean at least 6 months, if I'm even still working on this program by then...So, I'll close this and re-examine when I cross that bridge if I do!
