### ISSUE TITLE
Feature request: Add a scraper tool

### ISSUE THREAD

**Issue by clickclack777** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#93]
With options

https://beautiful-soup-4.readthedocs.io/en/latest/

**Comment by BBC-Esq** [comment]
This program's goal is to remain as local as possible, not accessing the Internet in any fashion unless required to, for example, download a model.  I'm aware of Beautiful Soup though...cool library.    If you'd like to add .htm and .html files to the list of compatible files list, however, please create a new issue.
