### ISSUE TITLE
Feature request: Show token count

### ISSUE THREAD

**Issue by clickclack777** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#94]
Show token count "token count: 647/32768" below Start/Stop recording buttons.

**Comment by BBC-Esq** [comment]
What is the 32768?  Are you referring to the total token limit of the LLM being run within LM Studio?

**Comment by clickclack777** [comment]
yes, it is the the context length.

**Comment by BBC-Esq** [comment]
I can't show the context length of an LLM within LM Studio.  You'd have to just keep looking there...It's a closed source program.
