### ISSUE TITLE
Feature request: delete all or single files from "Docs_to_DB" from GUI

### ISSUE THREAD

**Issue by clickclack777** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#96]
There is no option anymore in 3.1.1 t reach the Docs to DB folder. Would be nice to be able to delete single or multiple files within the GUI.

**Comment by BBC-Esq** [comment]
You can select one or more files in the new tab that shows the documents and images currently in the vector database...just right click and click delete.

**Comment by clickclack777** [comment]
OK, not that intuitive and user friendly IMHO.
