### ISSUE TITLE
Feature request: Add html support for embedding

### ISSUE THREAD

**Issue by clickclack777** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#97]
Add html support for embedding

**Comment by BBC-Esq** [comment]
Actually, even though it's not listed in the instructions, i see that correct loader already in my scripts.  Can you try a html file?

**Comment by clickclack777** [comment]
OK, I´m getting this traceback when embedding them:

create_database.py: Loading documents.
document_processor.py: Number of workers assigned: 3
unstructured - /Users/click/miniforge3/envs/chromalm/lib/python3.11/site-packages/unstructured/documents/xml.py:105 - from_string
unstructured - /Users/click/miniforge3/envs/chromalm/lib/python3.11/site-packages/unstructured/documents/xml.py:105 - from_string
unstructured - /Users/click/miniforge3/envs/chromalm/lib/python3.11/site-packages/unstructured/documents/html.py:151 - _parse_pages_from_element_tree
unstructured - /Users/click/miniforge3/envs/chromalm/lib/python3.11/site-packages/unstructured/documents/html.py:151 - _parse_pages_from_element_tree
unstructured - /Users/click/miniforge3/envs/chromalm/lib/python3.11/site-packages/unstructured/documents/xml.py:105 - from_string
unstructured - /Users/click/miniforge3/envs/chromalm/lib/python3.11/site-packages/unstructured/documents/html.py:151 - _parse_pages_from_element_tree
document_processor.py: Number of NON-IMAGE files loaded: 1
document_processor.py: Number of NON-IMAGE files loaded: 2
document_processor.py: Number of NON-IMAGE files loaded: 3
document_processor.py: Loading images, if any.
No files detected in the 'Images_for_DB' directory.
create_database.py: Successfully loaded documents.
document_processor.py: Splitting documents.
document_processor.py: Number of Chunks: 25
document_processor.py: Chunks between 1 and 100 characters: 0
document_processor.py: Chunks between 101 and 200 characters: 1
document_processor.py: Chunks between 201 and 300 characters: 0
document_processor.py: Chunks between 301 and 400 characters: 2
document_processor.py: Chunks between 401 and 500 characters: 1
document_processor.py: Chunks between 501 and 600 characters: 2
document_processor.py: Chunks between 601 and 700 characters: 6
document_processor.py: Chunks between 701 and 800 characters: 13
create_database.py: Creating embeddings.
sentence_transformers.SentenceTransformer - /Users/click/miniforge3/envs/chromalm/lib/python3.11/site-packages/sentence_transformers/SentenceTransformer.py:66 - __init__
create_database.py: Embedding model loaded.
create_database.py: Creating database.
Traceback (most recent call last):
  File "/Users/click/ChromaLM331/src/gui_threads.py", line 7, in run
    create_database.main()
  File "/Users/click/ChromaLM331/src/create_database.py", line 63, in main
    db = Chroma.from_documents(
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/click/miniforge3/envs/chromalm/lib/python3.11/site-packages/langchain/vectorstores/chroma.py", line 771, in from_documents
    return cls.from_texts(
           ^^^^^^^^^^^^^^^
  File "/Users/click/miniforge3/envs/chromalm/lib/python3.11/site-packages/langchain/vectorstores/chroma.py", line 707, in from_texts
    chroma_collection = cls(
                        ^^^^
  File "/Users/click/miniforge3/envs/chromalm/lib/python3.11/site-packages/langchain/vectorstores/chroma.py", line 120, in __init__
    self._client = chromadb.Client(_client_settings)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/click/miniforge3/envs/chromalm/lib/python3.11/site-packages/chromadb/__init__.py", line 248, in Client
    return ClientCreator(tenant=tenant, database=database, settings=settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/click/miniforge3/envs/chromalm/lib/python3.11/site-packages/chromadb/api/client.py", line 139, in __init__
    super().__init__(settings=settings)
  File "/Users/click/miniforge3/envs/chromalm/lib/python3.11/site-packages/chromadb/api/client.py", line 43, in __init__
    SharedSystemClient._create_system_if_not_exists(self._identifier, settings)
  File "/Users/click/miniforge3/envs/chromalm/lib/python3.11/site-packages/chromadb/api/client.py", line 50, in _create_system_if_not_exists
    new_system = System(settings)
                 ^^^^^^^^^^^^^^^^
  File "/Users/click/miniforge3/envs/chromalm/lib/python3.11/site-packages/chromadb/config.py", line 313, in __init__
    if settings[key] is not None:
       ~~~~~~~~^^^^^
  File "/Users/click/miniforge3/envs/chromalm/lib/python3.11/site-packages/chromadb/config.py", line 250, in __getitem__
    raise ValueError(LEGACY_ERROR)
ValueError: You are using a deprecated configuration of Chroma.

If you do not have data you wish to migrate, you only need to change how you construct
your Chroma client. Please see the "New Clients" section of https://docs.trychroma.com/migration.
________________________________________________________________________________________________

If you do have data you wish to migrate, we have a migration tool you can use in order to
migrate your data to the new Chroma architecture.
Please `pip install chroma-migrate` and run `chroma-migrate` to migrate your data and then
change how you construct your Chroma client.

See https://docs.trychroma.com/migration for more information or join our discord at https://discord.gg/8g5FESbj for help!
