### ISSUE TITLE
Issue when embedding db in 3.1.1 -> ValueError: You are using a deprecated configuration of Chroma.

### ISSUE THREAD

**Issue by clickclack777** [BBC-Esq/ChromaDB-Plugin-for-LM-Studio#99]
create_database.py: Loading documents.
document_processor.py: Number of workers assigned: 10
document_processor.py: Number of NON-IMAGE files loaded: 3
document_processor.py: Number of NON-IMAGE files loaded: 6
document_processor.py: Number of NON-IMAGE files loaded: 9
document_processor.py: Number of NON-IMAGE files loaded: 12
document_processor.py: Number of NON-IMAGE files loaded: 15
document_processor.py: Number of NON-IMAGE files loaded: 18
document_processor.py: Number of NON-IMAGE files loaded: 21
document_processor.py: Number of NON-IMAGE files loaded: 22
document_processor.py: Number of NON-IMAGE files loaded: 25
document_processor.py: Number of NON-IMAGE files loaded: 28
document_processor.py: Number of NON-IMAGE files loaded: 31
document_processor.py: Loading images, if any.
No files detected in the 'Images_for_DB' directory.
create_database.py: Successfully loaded documents.
document_processor.py: Splitting documents.
document_processor.py: Number of Chunks: 308
document_processor.py: Chunks between 1 and 100 characters: 3
document_processor.py: Chunks between 101 and 200 characters: 8
document_processor.py: Chunks between 201 and 300 characters: 19
document_processor.py: Chunks between 301 and 400 characters: 24
document_processor.py: Chunks between 401 and 500 characters: 29
document_processor.py: Chunks between 501 and 600 characters: 54
document_processor.py: Chunks between 601 and 700 characters: 85
document_processor.py: Chunks between 701 and 800 characters: 86
create_database.py: Creating embeddings.
sentence_transformers.SentenceTransformer - /Users/click/miniforge3/envs/chromalm/lib/python3.11/site-packages/sentence_transformers/SentenceTransformer.py:66 - __init__
create_database.py: Embedding model loaded.
create_database.py: Creating database.
Traceback (most recent call last):
  File "/Users/click/ChromaLM331/src/gui_threads.py", line 7, in run
    create_database.main()
  File "/Users/click/ChromaLM331/src/create_database.py", line 63, in main
    db = Chroma.from_documents(
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/click/miniforge3/envs/chromalm/lib/python3.11/site-packages/langchain/vectorstores/chroma.py", line 771, in from_documents
    return cls.from_texts(
           ^^^^^^^^^^^^^^^
  File "/Users/click/miniforge3/envs/chromalm/lib/python3.11/site-packages/langchain/vectorstores/chroma.py", line 707, in from_texts
    chroma_collection = cls(
                        ^^^^
  File "/Users/click/miniforge3/envs/chromalm/lib/python3.11/site-packages/langchain/vectorstores/chroma.py", line 120, in __init__
    self._client = chromadb.Client(_client_settings)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/click/miniforge3/envs/chromalm/lib/python3.11/site-packages/chromadb/__init__.py", line 248, in Client
    return ClientCreator(tenant=tenant, database=database, settings=settings)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/click/miniforge3/envs/chromalm/lib/python3.11/site-packages/chromadb/api/client.py", line 139, in __init__
    super().__init__(settings=settings)
  File "/Users/click/miniforge3/envs/chromalm/lib/python3.11/site-packages/chromadb/api/client.py", line 43, in __init__
    SharedSystemClient._create_system_if_not_exists(self._identifier, settings)
  File "/Users/click/miniforge3/envs/chromalm/lib/python3.11/site-packages/chromadb/api/client.py", line 50, in _create_system_if_not_exists
    new_system = System(settings)
                 ^^^^^^^^^^^^^^^^
  File "/Users/click/miniforge3/envs/chromalm/lib/python3.11/site-packages/chromadb/config.py", line 313, in __init__
    if settings[key] is not None:
       ~~~~~~~~^^^^^
  File "/Users/click/miniforge3/envs/chromalm/lib/python3.11/site-packages/chromadb/config.py", line 250, in __getitem__
    raise ValueError(LEGACY_ERROR)
ValueError: You are using a deprecated configuration of Chroma.

If you do not have data you wish to migrate, you only need to change how you construct
your Chroma client. Please see the "New Clients" section of https://docs.trychroma.com/migration.
________________________________________________________________________________________________

If you do have data you wish to migrate, we have a migration tool you can use in order to
migrate your data to the new Chroma architecture.
Please `pip install chroma-migrate` and run `chroma-migrate` to migrate your data and then
change how you construct your Chroma client.

See https://docs.trychroma.com/migration for more information or join our discord at https://discord.gg/8g5FESbj for help!

**Comment by BBC-Esq** [comment]
I've had no problems on my end...You must install the Chroma version indicated in my requirements.txt files.  Please doublecheck that you didn't accidentally not use a virtual environment when running the program or somehow installed a newer version of chroma.  You can also try pip uninstall, then reinstall the specific version.

**Comment by clickclack777** [comment]
OK, thanks. Solved it by regressing the chroma version.
